### ISSUE TITLE
Order Screen - Show Secondary Warehouse qty columns 

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#110]
![image](https://user-images.githubusercontent.com/36732084/40460639-51a21906-5f3a-11e8-865b-51032453b5da.png)

Could you add columns to the Column chooser for the Secondary Warehouse 1, Secondary Warehouse 2, Secondary Warehouse 3, Secondary Warehouse 4 &  Secondary Warehouse 5 and it would show name of warehouse in the column title then the result would be the available quantity in that warehouse.

**Comment by bLeenstra** [comment]
This would likely make the order screen very slow, and as such wont be added unless there are additional requests for this
