### ISSUE TITLE
Folder Structure Option for Call Schedule Or Grouping?

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#111]
Would it be beneficial to have a similar grouping as the Parent folder setup for status lists. 

we have a fair chunk of technicians in our schedule now. making it collapse or group able by manager or something might make it easier to read.

**Comment by samuelGrahame** [comment]
if we just allowed you to specify the category/type of technician would that work. that way i we could just add a group by column .

**Comment by AnthonyLorraine** [comment]
could we group by Employee Management > Primary Manager?
![image](https://user-images.githubusercontent.com/36732084/40523852-22ba9ffc-600a-11e8-934c-a6ea4238fce9.png)

**Comment by samuelGrahame** [comment]
i will look into it

**Comment by samuelGrahame** [comment]
this will be in the next update

**Comment by bLeenstra** [comment]
Removed images with identifying information
