### ISSUE TITLE
Inventory Serial Number - Issues

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#123]
On print Docket Preview it shows supplier invoice, used to show serial number. The customer needs the serial number supplied in case they need to claim warranty at a later date. This inventory item is ticked after being received as having a serial. Shouldn't the Docket preview update correctly? but with no serial number?

![image](https://user-images.githubusercontent.com/36732084/40595957-6d2967b4-626a-11e8-9e45-0831a6e414c9.png)

Can it be made if we tick the "serialized stock" option after receiving the goods incorrectly that it updates the repair with the serial number on that order?

![image](https://user-images.githubusercontent.com/36732084/40595947-5dc71604-626a-11e8-8203-8d6c20739d03.png)
![image](https://user-images.githubusercontent.com/36732084/40595985-970f64e8-626a-11e8-8585-4e0bf4f26c6b.png)

We can rectify this error only by removing the inventory line from the repair, clicking save, opening the Inventory item, clicking Add Serial, add the serial, Save inventory and re-adding it to the repair. This will then show up the serial number.

![image](https://user-images.githubusercontent.com/36732084/40596014-c38f6504-626a-11e8-8385-6495ffe33efa.png)

**Comment by samuelGrahame** [comment]
added - When you modify the serial number on the order, it will workout if the has no serial numbers assigned. if there is none assigned it will create a serial number and assign it to the repair/sale item.

will be in the next version
