### ISSUE TITLE
Part Status - Picking Slips / View Items not sent

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#130]
Please assist with creating/finalising part status for sending parts from warehouse (showing this status at the bottom as well as top).  We will use this for tracking where the part is.  By using this feature we will also be able to provide a list of items that have been picked/sent to the techs (this will also be a checklist for the techs to mark off parts that the techs have received)

**Comment by samuelGrahame** [comment]
this has been added to the program. will be in the next update

**Comment by sydapp992** [comment]
Hi Samuel,

we're currently getting parts on order in the picking slip. if the part goes on order can you create a status to stay on that till the part arrive then soon as it marked off as received jump in to prepare to send?
