### ISSUE TITLE
Bulk Close/Transfer of jobs from WQA to Cancelled/Quote Rejected

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#131]
We would like the ability to remove a list of jobs from WQA to Cancelled/Quote Rejected Status. At the moment they can only be moved to Finalized.  We would prefer to use Completed Status sales/repairs for jobs with a $ value.  Thank you

**Comment by bLeenstra** [comment]
Notes: Status movement currently doesn't allow moving jobs with WQA parts. Need to allow moving jobs with WQA parts to other WQA status's for this

**Comment by samuelGrahame** [comment]
requirements: check each job/sale if they can be converted. if they are a quote status then allow to convert quote status to quote status.

also no finalized jobs can be touched using this...

if quote status to non quote status check if those quotes don't have parts.
if non quote to quote - check if those non quotes have no parts.

**Comment by AnthonyLorraine** [comment]
This (#35) is the same request.

**Comment by bLeenstra** [comment]
Closing as issue is already tracked
