### ISSUE TITLE
The ability to overwrite Primary Allocation

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#132]
We need your help with 2 features/processes.
1. Restrict Access for staff to only use the recommended technician as the primary allocation (lock system down) - per Jodie's request
2. Restrict Access, if parts are on a job. You need special permission to transfer that job to another tech.  I did try using "The ability to overwrite Primary Allocation".  This then restricts all access and staff cannot allocate  to techs at all.  We need to make sure that all the unfitted parts have been returned to the previous techs van stock, before the switch happens.

Thank you

**Comment by samuelGrahame** [comment]
"The ability to overwrite Primary Allocation" this permission is for the point 1.

for point 2

<b>Ability to Re-Allocate a Technician</b> when there are part's attached to a job.
added the permission

will be in the next version.
