### ISSUE TITLE
Lumley - Copy Paste function missing some data

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#134]

**Comment by bLeenstra** [comment]
Please clarify what information is missing

**Comment by sydapp992** [comment]
Please change Flag to Extended warranty and DOP details are not being updated.  Thanks

**Comment by bLeenstra** [comment]
I have adjusted the process to set the warranty type to Extended warranty for lumley.
Can i get you to email me a sample of their work order so i can enter the DOP

**Comment by bLeenstra** [comment]
Closing old Request without required follow-up.
Feel free to reopen the issue if you have the additional information

**Comment by bLeenstra** [comment]
Repoening as sample data provided

**Comment by bLeenstra** [comment]
added for v399
