### ISSUE TITLE
Mark off remittance Via Upload - Accounts Receivable

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#135]
To be able to Upload/Bulk to mark off a remittance - Excel format that can be used to mark off multiple lines for the same customer
Eg.
Charge to   Repair#   Amount   Type (BD etc)
This process for a large remittance could take several hours for 1 person to do.

This would be a huge enhancement to BM.  I could be out of a job !!!!

Thank You Maria

**Comment by sydapp992** [comment]
Hi Samuel,  Could you please advise when this can be created.   The Amount Type Would be Cash, Cheque, Direct Deposit, Mastercard ETC.  I am spending alot of time everyday marking off remittances.  This will be great help to to businesses.  Thank you

>

**Comment by samuelGrahame** [comment]
just so i can refresh my memory.
file format would be: 
Repair Number, Amount to pay (even if it is an over payment), Payment Type

**Comment by samuelGrahame** [comment]
I will call you to go over this.

**Comment by samuelGrahame** [comment]
This has been completed
