### ISSUE TITLE
Consignment List Screen - Opens as incorrect card type

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#138]
Opening jobs from the Consignment list screen seems to only open them up as sales. When you go to modify the job it changes it to a repair with the pop up "This has been converted to a repair, would you like to open the repair?" 

Not a major issue but a small bug. 

![image](https://user-images.githubusercontent.com/36732084/40697308-3be48bbe-63fc-11e8-8adb-eed2a149e539.png)

**Comment by samuelGrahame** [comment]
I will fix this now

**Comment by samuelGrahame** [comment]
this has been fixed in the development version. will go live in the next version

**Comment by bLeenstra** [comment]
Removed images with identifying information
