### ISSUE TITLE
Goods Receiving - Auto-Transfer & Add to Sale (Auto-Transfer to Repair)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#14]
When we receive goods into Intelogy, currently the system doesn't always transfer the spare parts to the job. 
This requires the user to open the **Repair** and go to the inventory received and click "transfer" and update the status of the repair to the correct status.

For **Sales** the user is required to go to the **Picking Slips**, search for the items that have been received in, tick the boxes for each item, right click and transfer. Then open the **Sale**, click "Add to Sale" and update the status of the sale to the correct status.

I know not every company using BM will require this, however, this task itself is very time consuming for our staff receiving goods.

Is it possible to have a General Preference for:

- Allow all items being received to be transferred to the repair or sale.
- Allow all items being received for a sale to be added to "used".

**Comment by samuelGrahame** [comment]
"Allow all items being received to be transferred to the repair or sale." are you referring to orders.

need to go over this so that i can make sure a procedure is correct.

**Comment by samuelGrahame** [comment]
There is a setting, so when you receive on orders. to go through the picking slips. it might be on by default and there might be a way of turning it off.

![image](https://user-images.githubusercontent.com/13449963/41383100-6f8bc1c8-6fb2-11e8-83e5-babac80ba446.png)

**Comment by samuelGrahame** [comment]
this has no been completed, i have tested it.

it requires that the sale is not locked.

**Comment by samuelGrahame** [comment]
to enable this setting:

![image](https://user-images.githubusercontent.com/13449963/41386877-40ee2c06-6fc7-11e8-8475-d9225ad26ee6.png)

above is the setting - it is under inventory tab

**Comment by AnthonyLorraine** [comment]
@samuelGrahame  For the repairs, will they transfer without requiring to go into the repair and clicking transfer. i have checked. we dont have the option "Use the picking slips screen for receiving orders" enabled.
