### ISSUE TITLE
Sales - New Customer vs Existing Customer

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#150]
When we create a new customer a popup appears asking if we would like to set the deliver to the same as the charge to.  Popup Window asks. Yes ? No?

Can this be made to ask the same question if charge to already exists?

**Comment by bLeenstra** [comment]
Was there any reason you where looking to do this?

If no deliver to is set the charge customer acts as the deliver to customer in the system.
If this is not working somewhere please let me know where so we can fix this issue in the system.

**Comment by AnthonyLorraine** [comment]
For our ordering in SA we use the service for/deliver to fields to determine where the order is shipped to. 
Any way we can get the popup to occur similar to a new customer as above?

**Comment by bLeenstra** [comment]
Complete for v369
