### ISSUE TITLE
Pending Repairs - Managed By

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#151]
Currently the filter doesnt filter how i imagined. please let me know if the below setup is correct

![image](https://user-images.githubusercontent.com/36732084/40826435-2b7b59ee-65ad-11e8-906f-fbf7b17be95f.png)

**Comment by bLeenstra** [comment]
The pending repairs managed by filter is linked to the charge customers managed by field.

**Comment by bLeenstra** [comment]
Removed images with identifying information
