### ISSUE TITLE
Employee Code for Action Plans

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#152]
Which code does this relate to? Employee number or Code?

![image](https://user-images.githubusercontent.com/36732084/40826500-5c722032-65ad-11e8-9f11-2080571b5831.png)

**Comment by bLeenstra** [comment]
Id relates to the internal employee id.

The action plans can only use information actually available on the repair screen, which the employee number is not.

**Comment by AnthonyLorraine** [comment]
can we view this internal ID somewhere on the employee card so i know where to link to?

**Comment by samuelGrahame** [comment]
added - in the new version:
employee CNTR will be in the employee window title

**Comment by bLeenstra** [comment]
Removed images with identifying information
