### ISSUE TITLE
Check if the job is locked onfocus for service report

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#158]
reason, puting in data - if job is locked lose all work

**Comment by bLeenstra** [comment]
More info: Regarding webFramework

**Comment by samuelGrahame** [comment]
when clicking on the service report. send a ajax request to checkif the current job is locked. show an alert if it is. (that way they can callup that person to unlock.) another option we can make timed locks. on eworks. if they open the job. if it is locked. they cant change. but if it isnt locked. a time lock is created for lets say one hour. each change they do. it resets the time to 1 hour.
