### ISSUE TITLE
Show in any of these parts are marked no longer available

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#160]
"I called and explained the problem with my TV and they said it sounds like a starter problem but they'd need to take a call out fee of $***** over the phone before sending someone which I did.  They sent someone out who confirmed the issue and said they'd get back to me with a cost for the part.  They called me and said the part is no longer available.  In my eyes, they've just ripped me off a call out fee because they knew full well the model and which part they might need.  They should have checked to see if this part was available because they knew that this was mostly likely the problem.  I wouldn't recommend ***** unless you are prepared to pay a call out fee even though they can't get the part you may need."

Solution warn when saving the repair. some of these parts are marked no longer available.

**Comment by bLeenstra** [comment]
Available for v369 
    - Bill of materials list will highlight parts that are no longer available
