### ISSUE TITLE
Attachments - Sort by date added - etc

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#166]

**Comment by samuelGrahame** [comment]
new attachments from the web framework will have create date now

**Comment by samuelGrahame** [comment]
requirements: use attachment date for new attachments from bm. make a fake date for items that don't have a date. but show blank. but the date is based off the CNTR

**Comment by samuelGrahame** [comment]
Added - if there is a datecreate - it will now sort by that value in the repair
