### ISSUE TITLE
Collection Method Rules

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#167]
When collection method is set to "Customer to Collect" there needs to be a feature which prevents the unit from being "Shipped back to Customer". My suggestion is if the Collection Method is set to "Customer to Collect" BM should blank out the rest of the data from being entered. i.e. "Consignment No" "Courier Name" etc. Hence preventing any units being shipped out if the customer is collecting.

**Comment by bLeenstra** [comment]
If "Customer to Collect" is selected and there is already existing Consignment No etc data should we remove that information when selecting "Customer to Collect"

**Comment by samuelGrahame** [comment]
adding a setting. for collection method. when changing Collection Method to: "Customer to Collect". Clear Consignment No, Courier Name. and other collection fields.

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/42921170-c274c134-8b5d-11e8-97ad-cc99e1136837.png)

When you change it to  - customer to collect; this is what it looks like
