### ISSUE TITLE
ETA - for WQA (top section) & print outs 

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#169]
1. Adding field available for ETA option to WQA (top section) & print outs 
2. When part is placed on order ETA should be updated on order status
3. When updating an ETA for parts on order, we require a standard email to be sent to the customer advising of delay (only if part is on order)

**Comment by bLeenstra** [comment]
Duplicate - See #21

**Comment by bLeenstra** [comment]
Closing as issue is already being tracked as per above
