### ISSUE TITLE
Search Screen inventory - Warehouse Reserve is not factored in

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#176]
Amount Available can be misleading here

**Comment by samuelGrahame** [comment]
Change column to Amount Including Reserves. 
as adding reverse might slow down the search to be not usable.

**Comment by samuelGrahame** [comment]
Add credit reserve

**Comment by samuelGrahame** [comment]
changed column to: Amount Including Reserves
