### ISSUE TITLE
Web Framework - Manufacturer - Allow sending reminders

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#177]
Needs to be added as a setting
    Manufacturer ether needs to be able to choose contact, or send to the manufacturers managed by employee
Reminder needs to somehow show who it was send by - could just set sendby cntr to -100 and display manufacturer as the name

**Comment by samuelGrahame** [comment]
This has been done for business manager light.
this will not be done for the web framework.
