### ISSUE TITLE
Sale Items Status field - Log changes in the repair activity

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#178]
See title

**Comment by samuelGrahame** [comment]
currently the date is requested on the sale item. what other fields would you need. etc who changed it.
potential could bloat the db

**Comment by samuelGrahame** [comment]
have this as an option. so if someone wants to track this. then they can

**Comment by samuelGrahame** [comment]
Part status changes - Prepare to Send to Sent adding a Time / Date & Who
