### ISSUE TITLE
Actions/View Items not Sent

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#179]
1. Count of line items showing on print out & Date/time printed
2. Add Tech Name to Van number
3. EWORKS requires a Received Status for tech (mark off)
4. Please ensure for that the List is not auto refresh to avoid any changes

**Comment by samuelGrahame** [comment]
Is this a report to show on Eworks or a report to show in BM.

4: done - 2: done. 1 needs to be done so does 3

**Comment by bLeenstra** [comment]
complete v379
