### ISSUE TITLE
Employee Management / Subcontractors Details - Additional fields needed

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#183]
Under the Sub-Contractor Trading Details - please assist with adding

PUBLIC LIABILITY Expiry
WORKERS COMPENSATION Expiry
COMPANY REGISTRATION Expiry

Thank you

**Comment by bLeenstra** [comment]
The license fields in the employee card can be renamed by double clicking the text label.
Please let me know if that provides you with enough license fields

**Comment by samuelGrahame** [comment]
no repsonce, we can add more fields.

**Comment by bLeenstra** [comment]
Closed - Reopen if you have additional information as requested above

**Comment by bLeenstra** [comment]
Need to allow for Adding additional licenses fields as required

**Comment by bLeenstra** [comment]
Available from v397 - setting will need to be installed from new features popup
