### ISSUE TITLE
Label for Major repairs

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#184]
hi,

can we get a label added for major repairs? with a tick box option?

![image](https://user-images.githubusercontent.com/39507077/41270578-5e0a30ba-6e4f-11e8-9faf-4879d7ac9765.png)

Dinu.

**Comment by samuelGrahame** [comment]
Will need to go over what a major repair is. to support creating more tick box options' we will need to move these to an another tab.

**Comment by samuelGrahame** [comment]
Added this now, will be in the next version

**Comment by bLeenstra** [comment]
In v379 as per above comment
