### ISSUE TITLE
Column layout not saving

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#185]
Column layout not saving also added column not staying on soon as refreshed goes away.

**Comment by bLeenstra** [comment]
To clarify - This is in the picking slip screen

**Comment by sydapp992** [comment]
it's all over none of the column layouts are saving. when i refresh and close window and open again same thing happens.

**Comment by bLeenstra** [comment]
Couldnt Reproduce locally, may be a combination of items making this issue occur

**Comment by samuelGrahame** [comment]
Closing this because old, i believe this was to do with picking slips.
