### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#187]
Hi Brendan / Samuel,

Is there any instructions on how to use the marketing system in Business Manager? Every year i get asked how to send out a PDF mail out and every year i forget LOL.

If not, can i get something to give to my marketing guys?

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/41382896-7d0af572-6fb1-11e8-94f0-193d0ffbb6b2.png)

use the following to setup the html document, which will allow you to send once you build the list and then you can send the marketing material.

**Comment by AnthonyLorraine** [comment]
can we send PDF attachment + HTML Body?

is it just HTML that will work here?, i'll have to use base64 for image right?

If i create a HTML Flyer with see attachment would this work?

**Comment by samuelGrahame** [comment]
hey, i will rework this screen to make it easier for marketing.

as at the moment, it is pretty hacky, when you send out content. it asks all these questions.
