### ISSUE TITLE
Repair - Other charge 3 - rounding decimals

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#19]
Issue where the other charge 3 would round up upon saving the repair,
Could not reproduce locally, might be an issue with the DB column type

**Comment by AnthonyLorraine** [comment]
Note on Other Charge 3, with Oth1 and Oth2, you can update the name of it and it will apply to all repairs. but with oth charge 3 its only applied to that repair.

**Comment by samuelGrahame** [comment]
added - allow to change global other charge 3 label
