### ISSUE TITLE
Pending Repairs - Auto Refresh Interval

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#193]
Can auto refresh be added to pending repairs?

**Comment by samuelGrahame** [comment]
it is possible

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/41388691-7995f788-6fd0-11e8-9c24-2efae256157d.png)

Added the Following to the pending repairs. minimum time in seconds is 5 seconds on refresh

it will be in the next version
