### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TEAW660** [IntelogyGroup/BusinessManagerIssues#195]
Operator '<>' is not defined for type 'DBNull' and type 'Integer'.   at Microsoft.VisualBasic.CompilerServices.Operators.CompareObjectNotEqual(Object Left, Object Right, Boolean TextCompare)   at Intelogy___Business_Manager.v8_DATA_Orders._Closure$__1539-0._Lambda$__0(DataRow a)   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Intelogy___Business_Manager.v8_DATA_Orders.RepositoryItemCheckEdit1_CheckedChanged(Object sender, EventArgs e)   at DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit.RaiseCheckedChanged(EventArgs e)   at DevExpress.XtraEditors.CheckEdit.set_EditValue(Object value)   at DevExpress.XtraEditors.CheckEdit.set_CheckState(CheckState value)   at DevExpress.XtraEditors.CheckEdit.Toggle()   at DevExpress.XtraEditors.BaseCheckEdit.OnMouseUp(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by TEAW660** [comment]
ticking awaiting approval credits

**Comment by bLeenstra** [comment]
Found probable cause of error.
Patch for v370
