### ISSUE TITLE
Action Plan - Repair/Sale Fields

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#201]
Can all the fields on a repair/sale be added to action plan so i can set highlight rules for them?

at minimum can the fields be added:
Mobile# charge and service for
Email charge and service for
Advertising charge and service for
Reference # 
Order # 
Courier Name

**Comment by AnthonyLorraine** [comment]
Department, Charge To State, Service for State

**Comment by bLeenstra** [comment]
Following items where already available
Reference #
Order #
Courier Name
Department

The following items where added
Mobile# charge and service for
Email charge and service for
Advertising charge and service for

charge/service state cannot be interacted with from action plans so this was excluded.
comparisions with this field can be done from the customerstate action plan


As of v379
