### ISSUE TITLE
Suggested Technician Notes

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#202]
Can the notes be more relevant to the engineer availability? per below images
Also can the layout be re-arranged and saved in this window on the repair/new booking?
Also can the layout be re-arranged in the Employee when setting up the postcode availability?

Currently Shows on new booking/new repair:
![image](https://user-images.githubusercontent.com/36732084/41516348-bc43b6ec-72e6-11e8-8295-e8c27aa5f303.png)

Can we use:

![image](https://user-images.githubusercontent.com/36732084/41516393-0acd18bc-72e7-11e8-8e1f-2ba214a3d161.png)

**Comment by bLeenstra** [comment]
The employee notes are relevant to booking to some businesses,
I will add another column for description instead
This will be done for v370

**Comment by AnthonyLorraine** [comment]
cheers :+1:

**Comment by AnthonyLorraine** [comment]
Hi @bLeenstra, I'm unsure if this is working as intended. can you login when you have some time to show me?

**Comment by bLeenstra** [comment]
Just send me login details over email when your available and i can go through this with you
------------------------------------------------------------------------
Removed images with identifying information

**Comment by bLeenstra** [comment]
- Needs to use Description from employee Areas available record as priority over zone item description

**Comment by bLeenstra** [comment]
fixed in v378

**Comment by bLeenstra** [comment]
Added requested features in v379
