### ISSUE TITLE
Highlight for Estimated Completion Date

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#203]
Dropdown field not working, but courier name does. Did i do something incorrectly?

![image](https://user-images.githubusercontent.com/36732084/41516469-88d9a3ce-72e7-11e8-9d1a-5847adfcb3de.png)

**Comment by samuelGrahame** [comment]
maybe because it is a different control type. i will look into it.

**Comment by bLeenstra** [comment]
Reference to estimate complete date did not exist for sales regarding action plan
This has been fixed in v379
