### ISSUE TITLE
Source Employee name not van

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#208]

**Comment by samuelGrahame** [comment]
also in the picking slips return item, v7 show there name too

**Comment by bLeenstra** [comment]
If this is only regarding the picking slips return items, this is already done for v370.

**Comment by sydapp992** [comment]
hi,

tech name is still missing on picking slips?

![image](https://user-images.githubusercontent.com/39507077/41759489-2e1dacd4-7632-11e8-879a-0330c5fa31f0.png)

**Comment by bLeenstra** [comment]
This was only added to the Not Returned List as per my original understanding of the request -> to show the assigned employee to the job for not returned items to easily see what had to be collected, and to also work out who to collect items from if there was no source location.

If you also want this on view items no sent, did you want it added in the same way as above, or should the employee name be shown based on the van

**Comment by bLeenstra** [comment]
Complete for v373
