### ISSUE TITLE
Return Slip on picking slips on print

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#210]

**Comment by bLeenstra** [comment]
Hi this issue is still open and has not been complete yet.
We will close the issue when it has been complete

**Comment by bLeenstra** [comment]
Removed images with identifying information

**Comment by samuelGrahame** [comment]
Added the names for the returned slip.

![image](https://user-images.githubusercontent.com/13449963/42976488-2700db7c-8c05-11e8-8b6e-ce7441d35c60.png)

will be in the next version
