### ISSUE TITLE
Attachment Labels - Mandatory Option

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#212]
Can it be made an option to be mandatory to have 1, 2 or all of these custom words required before clocking off a job?

![image](https://user-images.githubusercontent.com/36732084/41570945-8548910e-73a3-11e8-8edd-a5642a4657ec.png)

**Comment by samuelGrahame** [comment]
requirements - Web Framework screen needs to allow re labeling already uploaded item's - also don't allow to upload attachments unless they press start. if they have not pressed start. maybe we press start for them

**Comment by AnthonyLorraine** [comment]
Do i need to provide further action here? or will this be in a future update?
