### ISSUE TITLE
SQL Required - Eworks/BM

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#214]
1. Need a report for the techs to view on E-works that lists parts unused from repairs that have been moved off a repair back to their remote inventory.

So if it has no unlink from a repair, would assume a min max change has occured and need to return his overage of stock?

QTY to Return,PART# to Return,DESC,JOB# removed from(or min/maxchange) ,DATEREMOVED.

Our current show items to be returned for ONE tech :(

![image](https://user-images.githubusercontent.com/36732084/41575187-8bf241a6-73b4-11e8-97ba-e13a78cb18fc.png)

2. Current Van stock shows all items including reserve items, can this only show "Van Stocked" items (min/maxed items).

can we discuss next week some time requirements here?

**Comment by samuelGrahame** [comment]
we have a new way atm, when removing stock
it hides on eworks
but shows up red down the bottom
in the picking slips it shows items to be returned.

**Comment by AnthonyLorraine** [comment]
can this new way be added so if BM user removes stock, it shows as items to be returned on the picking slips too. Currently only works through Eworks correct?

**Comment by samuelGrahame** [comment]
yes that is correct. as people have access to the warehouse.

so i guess this should work for this situation:
someone removes that part off the job. but it is transferred to the van. it should go to returned parts.
