### ISSUE TITLE
Van Stock - Job Allocating

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#217]
Basically our issue is that its too hard to track if the technician has sufficient quantities of his van stock per day for all his required repairs, then when he doesn't, reissue from warehouse by allocating to the job. 

_Note:
We do a van replenishment order + replenish from stock each day. We're leaning towards just van ordering for items that are going to arrive for the next morning, and replenish from warehouse for items that wont arrive. The warehouse will stock all overages required for each day.
So the below would have to take this into account._

Proposed Setup:

1. Need to be able to visually see the difference in location the stock is coming from
1. Need to see visually on call schedule if tech requires more stock, or automatically when assigning, NOT ENOUGH STOCK do you want to take from warehouse, then if no stock in w/h, order (Stock Control Screen).
1. Need to only assign invoice numbers when used, only control levels of stock? not certain if this is crucial but the van reserves need to always be returned to van they're reserved from. If tech change it needs to release that stock from that tech and recalculate for new technician.
1.  On E-Works, tech to be able to easily view which is coming from his van reserve, which is coming from warehouse reserve, which has been ordered and which has been fitted already.
1. Van reserve items to be easily added if tech used by clicking Add to job etc.

![image](https://user-images.githubusercontent.com/36732084/41638402-c28a021c-748b-11e8-89d9-ff2fd794337a.png)

Current Setup:
_We use Non-Inventory Items name VAN.STOCK.AVAIL to track our van stock items, for how many we require each day. So if the amount of this non inventory item is over the amount available in the technicians van we do an over replenishment or just simply assign parts from warehouse to this job._

![image](https://user-images.githubusercontent.com/36732084/41635904-e5515114-747d-11e8-84ec-043e11d35dfd.png)

May need to discuss requirements as it is difficult to completely relay this information written.

**Comment by bLeenstra** [comment]
Marking duplicate as this is essentially #272
