### ISSUE TITLE
Action Plans/System Addition - Departments for Sales

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#218]
Would this be best through departments or a system setting?

To eliminate human error. Our branches are multi state, can we have it so if we create a sale for a customer that is in SA, it be set to our department there. same for WA, if WA then WA Sale etc.

We are going to be going to departments on Sunday, can this one be sorted prior to then? sorry for short notice, ive only been testing for less than a week on departments.

**Comment by bLeenstra** [comment]
Sales/Repairs are automatically assigned to the technicians department when allocating the job to the technician, which should be sufficient for this.

**Comment by AnthonyLorraine** [comment]
:( you don't like my **URGENT** flag

**Comment by bLeenstra** [comment]
Added it to an urgent tag instead, easier to see and less distracting when scrolling through the list of issues

**Comment by bLeenstra** [comment]
Just following up here since this is marked as urgent,
Does my above answer work for you, and if not please go over why.
Otherwise feel free to close this issue.

**Comment by AnthonyLorraine** [comment]
How do i allocate a technician to a sale?

**Comment by bLeenstra** [comment]
I have added departments to the action plans for v373.

However please note that for the set value part of action plans to work the user needs to be able to see the department field on the sale/repair screen (which mean they need the change departments permission for the set action plan to work).

The check part of the action plan will work regardless however.

**Comment by bLeenstra** [comment]
v373 Released - Item now closed

**Comment by AnthonyLorraine** [comment]
Please show me how this can work before staff put inventory on a sale, thanks.

**Comment by bLeenstra** [comment]
A new action plan type to trigger before parts are added was created in v374. This will allow you to accomplish this.

Feel free to close this issue once you have the update

**Comment by AnthonyLorraine** [comment]
testing this, if needs further work i will reopen. thank you for your help Brendan.
