### ISSUE TITLE
Unassigned Vans - Show in Inventory Setup (Option to not show)?

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#219]
Can we have this removed if van isnt allocated. that way only shows relevant data?

![image](https://user-images.githubusercontent.com/36732084/41639497-960c2a30-7490-11e8-9d7a-3d6cbd8819bc.png)

**Comment by bLeenstra** [comment]
If these vans are not allocated to anyone and no longer used (no stock - ect), you can simply delete the van from "Main Screen" -> "Inventory" -> "Remote Locations" -> "Delete".

**Comment by AnthonyLorraine** [comment]
Wont this delete all history of all parts for that vehicle? so if we needed to refer back to it we cant?

**Comment by bLeenstra** [comment]
Ok I will add a setting to hide unassigned vans from the remote inventory screen

**Comment by bLeenstra** [comment]
Added as a preference for v372 - will be available under "General Preferences" -> "Inventory" ->"Hide Unallocated Vans from the remote inventory grid"

**Comment by bLeenstra** [comment]
Removed images with identifying information
