### ISSUE TITLE
Purchase & Sales History (Departments) Doesn't Refresh

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#220]
Data for Perth department.
![image](https://user-images.githubusercontent.com/36732084/41639667-54903d3e-7491-11e8-80fb-a1d985ddb72c.png)

Incorrectly shown data for Adelaide
![image](https://user-images.githubusercontent.com/36732084/41639692-7daa41ba-7491-11e8-9055-02aee924de67.png)

After changing the drop down to anything and back to view all it refreshes this data to show correct for that department. shown below.
![image](https://user-images.githubusercontent.com/36732084/41639724-972ff3c8-7491-11e8-8c11-dc98fb18275d.png)

**Comment by AnthonyLorraine** [comment]
Purhcase and sales summary also doesnt update

**Comment by bLeenstra** [comment]
These items where set to only load on opening the part or changing the history range to increase speed when modifying the part.
I have added a procedure to forcefully refresh this information when changing department
Fixed for v370
