### ISSUE TITLE
Auto words - Order/Credit Reference No.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#221]
So we have option to key in some data or use the dropdown pre-text. as we currently sort by this field.

**Comment by bLeenstra** [comment]
Removed images with identifying information
Hightlighted field was order details -> reference number

**Comment by bLeenstra** [comment]
complete in v379
Added order reference to programmable wording to fill in information
Added a dropdown to allow you to select items from autoword
