### ISSUE TITLE
Credit Form - Credit status information

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#222]
Can check boxes be added that add time stamps, similar to repairs with collected/returned to customer etc.
 for better tracking of credits.

or instead of #221 Could there be a Order Status that gets updated based on the request status.
Credit Requested, when we send our request via email or phone, pending approval.
Credit approved, when we get correspondence via email or phone to send it back.
Credit despatched, After goods have been despatched, willr equire consignment info.
credit completed, after credit note has been applied to the credit. and bill generated etc.

![image](https://user-images.githubusercontent.com/36732084/41640894-f7c66e02-7495-11e8-8a97-0dd29f026ce9.png)

**Comment by AnthonyLorraine** [comment]
there can be a delay between approval and despatch especially here in WA. this is why it would be a nice status to have too.

**Comment by AnthonyLorraine** [comment]
In addition, or immediately can we get under the View button the Activity log similar to the sales repairs or a inventory transaction to be recorded whenever parts are put onto a credit, then ticked as awaiting approval. currently there is no way to track an item that goes onto a credit as awaiting approval or anyway that it was removed.

**Comment by samuelGrahame** [comment]
I have added Is Approved for Credits and Date and who Checked Approved

**Comment by samuelGrahame** [comment]
I have renamed Delvery Details to Return Details when a Credit
I have renamed Sent By to Requested By for Credits

**Comment by samuelGrahame** [comment]
Added Consignment Number and Date Dispatched for Credits

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/50670850-32e03e00-1022-11e9-9ff0-36d9022e6067.png)

**Comment by samuelGrahame** [comment]
Recorded - if they undo awaiting approval in event viewer

**Comment by samuelGrahame** [comment]
Added - Record if added to awaiting approval
