### ISSUE TITLE
Sending Statements for All Debtors - Bug

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#223]
The specified string is not in the form required for an e-mail address.   at System.Net.Mail.MailAddressParser.ReadCfwsAndThrowIfIncomplete(String data, Int32 index)   at System.Net.Mail.MailAddressParser.ParseDomain(String data, Int32

**Comment by bLeenstra** [comment]
The error message is indicating that one of your debtors has an invalid email address set for their accounts email.
I can apply a fix so we will only attempt to send the email if the email address set is valid, but that wont result in the debtor that caused this error to appear to get their statement.

**Comment by bLeenstra** [comment]
I have made the above changes for v370
