### ISSUE TITLE
Permissions - Merge on Sales & Reminder Inbox

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#224]
Hi,

could you please advise what the permissions required to access Reminder Inbox and use the Merge feature on sales are?

Cheers

**Comment by bLeenstra** [comment]
Reminders use the Reminders permission
Merge Parts currently uses the Administrator permission

**Comment by bLeenstra** [comment]
upon researching, i see that merge parts already has its own permission, i have fixed the merge parts button on the sales screen to use that permission for v372

**Comment by bLeenstra** [comment]
Clicking the inbox button will allow him to open that screen, assuming his "Cannot Create New Records" permission is not set to true
