### ISSUE TITLE
E-Works Autoword Label for attachments 

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#228]
Doesnt let the technician save on eworks when using a label for attachment. works fine without the labels.

**Comment by bLeenstra** [comment]
Just tested this on my end, all seems to working correctly.
Can you please clarify what is not working here?

**Comment by AnthonyLorraine** [comment]
I will ask tech if he has had further issue. as i just tested on a diff tech name and worked fine too.
