### ISSUE TITLE
BOM List for Models with parts

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#229]
After moving to departments, we have incorrect data showing on our BOM list for adelaide repairs.

please advise.

![image](https://user-images.githubusercontent.com/36732084/41830331-ceb7000e-7872-11e8-83fc-271db67fa47f.png)

**Comment by bLeenstra** [comment]
Assuming you are referring to the warehouse available / reserve here.
If so i have found and fixed the issue for v377.

If incorrect data is referring some some other part of the screen please highlight the incorrect data for me so i know what to look at.

If my assumption was correct please feel free to close the issue

**Comment by AnthonyLorraine** [comment]
Oops sorry, will highlight next time.

**Comment by bLeenstra** [comment]
Removed images with identifying information
