### ISSUE TITLE
Remote Location Manager

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#230]
Any way to make this screen quicker, its even slower now we use departments

**Comment by bLeenstra** [comment]
Look into Speed Improvements to be made for the remote location manager

**Comment by bLeenstra** [comment]
v377 ships with significant speed improvements to this screen.

**Comment by AnthonyLorraine** [comment]
Amazing, thank you!

**Comment by AnthonyLorraine** [comment]
I cannot view warehouse anymore in remote location for either department. pls advise

**Comment by AnthonyLorraine** [comment]
![image](https://user-images.githubusercontent.com/36732084/42256442-f5a5ffcc-7f83-11e8-8f74-5e19245c9300.png)

![image](https://user-images.githubusercontent.com/36732084/42256455-013204da-7f84-11e8-90a2-860ce59f40a2.png)

**Comment by bLeenstra** [comment]
Fixed in v378
