### ISSUE TITLE
Action Plan not working 

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#232]
![image](https://user-images.githubusercontent.com/36732084/41883535-a594dc3c-7921-11e8-8a37-7981c5ea5007.png)

this will appear for other credit term types too.

**Comment by bLeenstra** [comment]
Hi Anthony,

Just had a look in code, it looks like comparing credit terms is setup to be done on their internal id, rather than their name

**Comment by AnthonyLorraine** [comment]
Is this correct code you are referring to?

	CASE 
		WHEN customers.CreditTermCNTR = 0	then 'Not Defined'
		WHEN customers.CreditTermCNTR = 2	then 'No Warranty'
		WHEN customers.CreditTermCNTR = 3	then '7 Days'
		WHEN customers.CreditTermCNTR = 4	then '28 Days'
		WHEN customers.CreditTermCNTR = 5	then '14 Days'
		WHEN customers.CreditTermCNTR = 6	then 'End Of Month'
		WHEN customers.CreditTermCNTR = 7	then 'Visa '
		WHEN customers.CreditTermCNTR = 9	then 'SecurePay EOM'
		WHEN customers.CreditTermCNTR = 10	then 'Secure Pay COD'
		WHEN customers.CreditTermCNTR = 11	then '15 Days from EOM'
		WHEN customers.CreditTermCNTR = 12	then 'No Credit - COD'
		WHEN customers.CreditTermCNTR = 13	then 'See main account'
		WHEN customers.CreditTermCNTR = 14	then '30 Days from EOM'
		WHEN customers.CreditTermCNTR = 15	then '45 days from 5th close off'
		WHEN customers.CreditTermCNTR = 17	then 'CEWA End of Month'
	end as 'Credit Terms',

**Comment by samuelGrahame** [comment]
Yes that is correct, you will need to use the numbers and not the string. atm

**Comment by AnthonyLorraine** [comment]
I must be doing something wrong, error still occurs on trade customer. using the below 

![image](https://user-images.githubusercontent.com/36732084/41890547-8c2cfa9c-7942-11e8-90af-ef7add23226c.png)

**Comment by AnthonyLorraine** [comment]
would it be "Not Filled Out" causing the issue?

**Comment by bLeenstra** [comment]
Charge Credit Terms is current pointed to the wrong item in code and will always be not filled out.
This will be adjusted in v378
