### ISSUE TITLE
Multi Departments - ICF Real Time Interface

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#233]
Currently only allows for one department to use the interface.
Can we have it choose based on State or from technician assigned etc?

**Comment by samuelGrahame** [comment]
Just got a question regarding this, Do the jobs still need to be assessed. aka assigned a technician. if so changing the technician will assign the correct department. assuming the end user who handles ICF jobs can change departments?
