### ISSUE TITLE
Order/Credit Screen (View Activity) + Bill screen option

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#234]
currently the activity screen shows nothing for orders/credits.

Can we have Bill number column added + Gen Pref option to show bill in front of order/credit screen after receiving credit note or invoice. Currently always pops up Behind the invoice, should be in front to confirm dollar values.

Could we see parts:

1. Added
2. Removed
3. Received
4. Marked as "Awaiting Return"
5. Marked as "Returned"
6. Return Reason changed from, to
1. Linked sale being unlinked and by who (This currently shows in the description of the part)
1. Pricing Changes from and to
2. invoice number changes from and to
3. if undo receive
4. quantity changes

![image](https://user-images.githubusercontent.com/36732084/41886221-137dd3f0-792e-11e8-8e1b-57535186b3be.png)

**Comment by bLeenstra** [comment]
Removed was already available in this activity log.
We will consider the other item if they are not already recorded elsewhere.
