### ISSUE TITLE
Stationary Setup - MultiDepartment

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#238]
Can each department have its own header for different information?

![image](https://user-images.githubusercontent.com/36732084/41894240-dd67684e-7950-11e8-8689-eea09139c4d8.png)

**Comment by samuelGrahame** [comment]
This can be done, but this can be done with custom printouts. as you just make two printouts.

**Comment by AnthonyLorraine** [comment]
Please show me, i would rather have it automated by department and not rely on people using a specific printout

**Comment by samuelGrahame** [comment]
Okay will have a look at doing different letter heads per department. If none is setup for the other department. It will use default. Will have to make this change




Get Outlook for Android







On Tue, Jul 3, 2018 at 4:15 PM +1000, "Anthony Lorraine" <notifications@github.com> wrote:












Please show me, i would rather have it automated by department and not rely on people using a specific printout

**Comment by AnthonyLorraine** [comment]
We are using custom printouts to fix this, it will show all branches for us. Thank you.
