### ISSUE TITLE
SQL to Update Inventory Pricing after setting up new plugin pricing.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#241]
Can we get an SQL to update all pricing in our system to reflect new Plugin pricing
separate by supplier. + an All Suppliers Option. Exclude "Lock this part from Automatic, Plugin price updates."

Another to show If flagged "Lock this part from Automatic, Plugin Price Updates.  Ill update these manually as there shouldn't be too many.

**Comment by AnthonyLorraine** [comment]
good point

Just do for all suppliers.
I was thinking a different way around, per supplier due to only one is having a price change at the moment. cheers.

**Comment by bLeenstra** [comment]
Further clarification again - you said only one supplier has a pricing change. have you actually set a plugin pricing structure?

**Comment by AnthonyLorraine** [comment]
![image](https://user-images.githubusercontent.com/36732084/41955469-b4d1eacc-7a12-11e8-8b6f-6cdee7c764fe.png)

we have our custom inventory price plugin, which i want to update. but if i make a change in here it wont update all stock in our stock file. which would be what this update SQL would be for.
Can you call 0430 514 556 when free and i can discuss further if need be. Cheers

**Comment by AnthonyLorraine** [comment]
Sorry, not to be pushy. 
Could this be done this month as SS release price update on 1/7.

**Comment by bLeenstra** [comment]
This will be added through a section in the inventory configuration with a button run the price plugin script on all parts / parts on selected supplier.

This will be in v377, which will ether be 29/6 or 2/7 depending on when it is completed

**Comment by bLeenstra** [comment]
Fixed in v378

**Comment by AnthonyLorraine** [comment]
not sure if you still wanted to do it. add p/n to the export file? 
The update seems to have worked this time on the same supplier we tried with before.

**Comment by bLeenstra** [comment]
v379
    - Added partnumber to export
