### ISSUE TITLE
Job Label - Needs Department Functionality added

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#242]
as title describes.

Our Adelaide department Job labels print with Bin location for Perth.

Show Remote name on Job Label if for a van or secondary location.
for Secondary Warehouse, use thier location, not warehouse location.

**Comment by bLeenstra** [comment]
Could you please clarify what functionality you believe here?

**Comment by bLeenstra** [comment]
Bin location - take department bin into account if available
Secondary Warehouse - show name

**Comment by bLeenstra** [comment]
Available in v377

**Comment by AnthonyLorraine** [comment]
Do i need to turn on a permission for this to work? does this go off the users department or the department of the repair/sale/stock? Locations are still incorrect.

**Comment by bLeenstra** [comment]
No permission required

The order item style version of this runs by the order department and the sale item style runs by the sale department. When you say locations are incorrect are you talking about binlocations or department? If i could see a copy you believe is incorrect and what it should show i can adjust the printout for you

**Comment by AnthonyLorraine** [comment]
Our Order 36646 example:

Part for Adelaide Branch 
![image](https://user-images.githubusercontent.com/36732084/42311009-5fcb1e32-806f-11e8-99f3-89c1fff45583.png)

Inventory Setup for that part (Adelaide)
![image](https://user-images.githubusercontent.com/36732084/42311038-746aa510-806f-11e8-9733-4ad8ea8bd0c0.png)

Inventory Setup for that part (Perth)
![image](https://user-images.githubusercontent.com/36732084/42311060-89f69cfe-806f-11e8-9356-d9e982b93e7a.png)

**Comment by bLeenstra** [comment]
Can you try adjust stock or set a bin into Adelaide?

This is likely because there is not a database entry for da92-00215D in Adelaide yet. 
Due to this the printout is picking up the "No Department" data, which the bin for will still be the same as the Perth bin.

**Comment by AnthonyLorraine** [comment]
I can try set that up, however, it should be if no bin in Adelaide, then no bin location should show on the label.

**Comment by bLeenstra** [comment]
This works like this so that this job label will work for people who do not have departments.
To resolve this we could clear your bin locations out of the no department part entry

**Comment by AnthonyLorraine** [comment]
would this create any errors for our current parts? if no issues, please update our data.

**Comment by bLeenstra** [comment]
Closed as per phone conversation

**Comment by AnthonyLorraine** [comment]
Issue is fixed per phone call. however could the Bin Location Cleanup Tool be updated to include departments? we did briefly talk about it on the phone.

**Comment by bLeenstra** [comment]
Created new issue #266 regarding the bin location cleanup tool
