### ISSUE TITLE
Custom Printout - Credit

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#247]
Can we have a drop down to select custom printout for credits please?

![image](https://user-images.githubusercontent.com/36732084/42142703-77d4340c-7de3-11e8-9b30-724c4e614175.png)

**Comment by samuelGrahame** [comment]
The printouts for credits/Order has not been done yet, do you mean for custom part labels?

**Comment by AnthonyLorraine** [comment]
I want to print a return label to A4. for shipping back to manufacturer.

**Comment by samuelGrahame** [comment]
which category is the label in?

or would you need a new category for return label/Printout

**Comment by AnthonyLorraine** [comment]
Could be a credits/orders category if there isn't already one. Maybe it might be better to seperate Orders/Credits as they have different requirements.
