### ISSUE TITLE
Status List -  Last Contact Log Time Column

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#25]
Add a column to the status list for the last status-movement time.
Might be slow

**Comment by samuelGrahame** [comment]
There is a Column called DIS - [Days in status] - could this be used. if we got the datetime's we could make DIS to a unbound column and Movement time column an unbound column

**Comment by bLeenstra** [comment]
Just went over communication with customer - this was meant to be time of last contact log entry - title has been edited accordingly

**Comment by bLeenstra** [comment]
Added to v355
