### ISSUE TITLE
parts received from an order not showing in transferred

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#250]

**Comment by samuelGrahame** [comment]
This is not an issue, There are two option's part orders get automatically transferred and handled from the order screen. or they go through picking slip's. This is by design.

**Comment by sydapp992** [comment]
Yes please, this will show all the parts that received in and also transferred from warehouse.

- thanks for removing,

**Comment by samuelGrahame** [comment]
This has been completed, will be in the next version
