### ISSUE TITLE
Techs removing parts off jobs / multipals

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#251]
Technician is unable to reduced multiple quantity given to job 1/3 - 2/3. if they remove the part(s) off parts jumps to warehouse instead to the van. if they try to re use the same part on same job again part is getting requested to pick from warehouse.

- Can the tech change the quantity used on job?
- if the tech remove parts off the job can that be move to van stock? but still show on return stock to warehouse?

**Comment by samuelGrahame** [comment]
The stock isn't getting removed to the warehouse. it is on reserve to the van for that job. they just can't see it.

originally before having the setting that requires "Not Returned Parts".
they would just be returned to the van.

I am working on the web framework re-working how the UI works to support phones/tablets better.

possibly this is something we can do. To allow them to change the qty. I can also allow the qty to include reserves for that tech for that part. when you click add.

so if they clicked remove on a part with 2 qty. then added 1 - the returned qty will be for 1. etc
but if they added 3 - then it can use 2 from the returned part for that tech, and also request to either 1 from the van/order/warehouse pick

**Comment by bLeenstra** [comment]
Labelled enhancement for UI improvement - webframework
