### ISSUE TITLE
Call Schedule - v377 shows 5 jobs, v378 shows 8.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#256]
Has something changed that i need to alter to show correctly?

V377
![image](https://user-images.githubusercontent.com/36732084/42310356-cb941c06-806d-11e8-830c-32c50b98de9f.png)
V378
![image](https://user-images.githubusercontent.com/36732084/42310386-df6c081a-806d-11e8-86ba-f143c96a0e5e.png)

Current job allocations:

![image](https://user-images.githubusercontent.com/36732084/42310405-ee6afb0a-806d-11e8-922b-c81ab674792a.png)

**Comment by bLeenstra** [comment]
As far as i can tell, nothing changed in this screen between these versions. can you tell me what van this relates to so i can investigate

**Comment by AnthonyLorraine** [comment]
This morning it seems to be showing correctly it was our VSA54 Van. I have screenshots showing full run information from each version that i can email to you if you would like to see.

**Comment by AnthonyLorraine** [comment]
![image](https://user-images.githubusercontent.com/36732084/42357253-91b00e04-8109-11e8-8960-2df9a704a9ce.png)
