### ISSUE TITLE
Timeclock Report

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#26]
SQL Report on our DB.

Timeclock report doesn't differentiate between system auto logoff or the user clicking exit to leave the program.
Our timeout is set to 60min so can lead to 1 hour variance in time worked for some employees.

**Comment by AnthonyLorraine** [comment]
Would there be a reason why logging to a TS would prevent the auto logoff feature after 60minutes?

![image](https://user-images.githubusercontent.com/36732084/40524275-48fd2426-600c-11e8-95cd-74a3bef8bdaf.png)

**Comment by bLeenstra** [comment]
This could be theoretically possible if the idle timer failed to start when loading the BM.

**Comment by bLeenstra** [comment]
Report was updated some time ago - closing issue for now.
Create new issue if the issue shown for TS2008 appears again
