### ISSUE TITLE
Bug Report - Add from Error Code

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#264]
Object reference not set to an instance of an object.   at Intelogy___Business_Manager.v8_Global_Functions.SearchForErrorCode(String ErrorCode, Int32 ModelCNTR, Int32 ManufacturerCNTR, Int32 DescriptionCNTR, Int32 ModelVersionCNTR, Int32 RemoteNameCNTR, v8_DATA_Repair data, v8_Class_Sale sale, Boolean limit1)   at Intelogy___Business_Manager.v8_Global_Functions.HandleErrorCodeFlow(v8_Class_Sale sale, v8_DATA_Repair data, List`1 ignoreCNTR)   at Intelogy___Business_Manager.v8_DATA_Repair.SimpleButton58_Click(Object sender, EventArgs e)   at System.Windows.Forms.Control.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by bLeenstra** [comment]
Couldn't Reproduce
However I have put in a fix for what i believe the cause might be for v379.
Please follow up with more error information if this continues to occur after v379
