### ISSUE TITLE
Unused bin location cleanup tool

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#266]
Create another copy to work with departments

**Comment by bLeenstra** [comment]
I will use my copy when i am ready to start working on this

**Comment by samuelGrahame** [comment]
Will be putting this in the system. so that departments will just work. if you would like to use this as a report. we can give you the name of the form. then just create an application link

**Comment by bLeenstra** [comment]
Attached associated reports.

[Bin location new.txt](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2212072/Bin.location.new.txt)

[Bin location.txt](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2212071/Bin.location.txt)

**Comment by bLeenstra** [comment]
Complete in v386
