### ISSUE TITLE
298573 Bug Report

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#267]
Parameter must be positive and < Width.Parameter name: x   at System.Drawing.Bitmap.SetPixel(Int32 x, Int32 y, Color color)   at Intelogy___Business_Manager.BitSlide.Paint(Int32 x, Int32 y, Boolean OnlyUseForeColor, Color ForeColor)   at Intelogy___Business_Manager.IntelogySignaturePanel.OnPaint(PaintEventArgs e)   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)   at System.Windows.Forms.Control.WmPaint(Message

![image](https://user-images.githubusercontent.com/36732084/42550289-7a25069c-8503-11e8-94c5-558472a8686b.png)

**Comment by bLeenstra** [comment]
Fixed in v379
Tech was somehow able to sign outside of the area available for signatures
