### ISSUE TITLE
Info Button on Repairs

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#27]
In **Data List Management**  can a manual tick box be added to have a name under the info button on repairs saying "Error code parts information available."

![image](https://user-images.githubusercontent.com/36732084/40159033-0da9b43a-59da-11e8-8283-bc4bf875f9e9.png)
![image](https://user-images.githubusercontent.com/36732084/40159060-279754ec-59da-11e8-9c6f-f40cbab1d625.png)

**Comment by samuelGrahame** [comment]
This will been on the next available version where we update the data structure.
