### ISSUE TITLE
Non-Inventory Sales not recorded per department

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#270]
We charge our gas out as non-inventory items. we track sales/purchase history. Now we have departments, I would like to see when a non-inventory item is sold to one department vs another.

**Comment by bLeenstra** [comment]
Fixed for v379 - 
department sale history was based on invoice numbers, which non inventory items do not have.
Created workaround to calculate when non inventory item
