### ISSUE TITLE
Allowing Vans to reserve stock from their own location

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#272]
Would there be a way to reserve items as van stock per day

The items would reduce van stock available to the transferred section, show on e-works for them to use van stocks. 
Then end of each job it would return available amounts back to van if unused.

i have no idea how this concept would work. Currently we're adding a non inventory item, replacing the description with the part number and description required for each van stock item required, then showing a print preview of the run and counting the amount needed for the day then supplying overage from warehouse.
This process can be easily missed and cause a failed service call due to no parts supply.

**Comment by bLeenstra** [comment]
Can you please go over why you add these parts as non inventory, rather than adding the actual part. As business manager calculates reserves based on the actual items waiting to be used.

**Comment by AnthonyLorraine** [comment]
phoned and explained to brendan.

**Comment by bLeenstra** [comment]
Clarifying Information
    - Need to be able to reserve stock from own van to job, rather than immediately adding part to the top.
    - Clear parts from van reserve when changing status if any left

**Comment by AnthonyLorraine** [comment]
Any update on this one?

**Comment by bLeenstra** [comment]
No update available for this. We will close the issue once added

**Comment by bLeenstra** [comment]
Included option to reserve stock from van in v399
