### ISSUE TITLE
Total Time Spent on Repair

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#273]
Can we have two total boxes one for Admin one for Technician? see image sent to Samuel on hangouts the clocked times are currently in the activity log. if it could be displayed simarly to the techs + total box.

**Comment by bLeenstra** [comment]
Can you please send me a copy so i can refer to it regarding this

**Comment by bLeenstra** [comment]
Complete in v379

**Comment by AnthonyLorraine** [comment]
Thanks for adding this. I have example in our system 298632. Unsure if this is 100% accurate, is there a way to try increase the accuracy of this. contact log shows a lot more staff in the job doing a fair few changes. not certain if this is due to patch being released midway through this job or not.

Can we also get the total value listed at the base or somewhere too?

**Comment by AnthonyLorraine** [comment]
300460 is another example. only microseconds being recorded?

**Comment by bLeenstra** [comment]
This timer tracks modified time when saving the repair in the same way the repair activity shows a log of the job being saved. 

One drawback of this is when business manager needs to save a repair for you while you are doing work in another screen (Adding Order item to repair from order screen, transferring items on the picking slip, etc) this will log the user as working in that related job for the milliseconds required to make that change and save the repair.

**Comment by AnthonyLorraine** [comment]
the millisecond transactions arent really an issue and are technically people spending time on a repair, however, the main modify/saves arent being recoreded at all. is there anyway this could be modified to show?

**Comment by bLeenstra** [comment]
Can you to give me an example job with a user that worked after the patch where it shows hours logged in the activity log but not the callcentre hours log?

**Comment by AnthonyLorraine** [comment]
job 3000460
![image](https://user-images.githubusercontent.com/36732084/43440036-5b975dfe-94c8-11e8-958b-55be2c7d2fb2.png)
maybe the hours should be converted to a legible time. 
currently shows 0.0147 for 12:29:43 to 12:30:36 but should be 53seconds etc.
Could it show if 0 then don't show else
1hour 1min 55sec
1min 55sec
55sec

**Comment by bLeenstra** [comment]
job 300460 shows the same number of items in the repair activity as the callcentre hours log.

I have created a new ticket #303 for hours formatting as that is a separate issue
