### ISSUE TITLE
SQL Report - Include Departments

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#275]
Could you please update this report to allow for departments, currently shows invalid data.

[Parts on Order where Parts in Stock.txt](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2199879/Parts.on.Order.where.Parts.in.Stock.txt)

**Comment by bLeenstra** [comment]
Please see updated SQL below.
You will need to add department as a selection for your report for this to work

[Parts.on.Order.where.Parts.in.Stock.txt](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2199941/Parts.on.Order.where.Parts.in.Stock.txt)
