### ISSUE TITLE
Stop Duplications

### ISSUE THREAD

**Issue by twebb6155** [IntelogyGroup/BusinessManagerIssues#278]
Hi Guys, Can we not have a prompt that pops up when creating a new sale/job etc whereby any details match a customer already in the system by checking phone number, abn etc etc. This would stop duplications from the start. It could prompt that somebody with the same details already exists and do you want to use customer already in the system or create a new one.

![image](https://user-images.githubusercontent.com/41351945/42916403-9fbe0478-8b37-11e8-88f8-7c16f063aa8b.png)

**Comment by bLeenstra** [comment]
This setting is already available under general preferences as
"When saving a new customer in a sale / repair, check to see if a similar customer already exists"

**Comment by bLeenstra** [comment]
Marked as to be closed - Just leave a message below if the above message does not fully answer your question.
