### ISSUE TITLE
Duplicate customer cleanup SQL

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#279]
see title.
show customers with same abn, mobile, address, merge all data on each account to 1 acc.

**Comment by bLeenstra** [comment]
Issues with creating a report to do this as it requires comparing a large number of strings against each other (need to check name / phone / address / etc). Would take too long to load the data.

Additionally, combining customers is a lossy transaction in terms of data, and therefore is not reversible, as such should not be automated
