### ISSUE TITLE
Orders/Credits on the Call Schedule

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#28]
- Enable Credits/Orders to be added to the call schedule. 

- On E-works, can you show that it is a Sale, Order, Credit or Repair on the run sheet

- Ability to add to contact log from eworks on a sale, credit or order.

- Add button "Delivered/Collected" to eworks on sale, credit or order. This would request a customer signature, invoice the sale and email out the invoice to the customer and update required fields.

- For Orders/Credits, can we have the signature for POD of credit back to supplier. 

- Add interactions to contact log with date/time stamp saying collected or delivered. *PrimaryAllocation*, *DateDelivered*or*DateCollected*.

**Comment by bLeenstra** [comment]
Including Orders/Credits in the call schedule will require a schedule overhaul.
Task to be considered when that occurs
