### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by victorappliances** [IntelogyGroup/BusinessManagerIssues#283]
when viewing run in google maps it shows the account address if the customer has differing account & serviced for addresses... or PO Box

**Comment by samuelGrahame** [comment]
- Comments - in the Data_Schedule.

**Comment by samuelGrahame** [comment]
In the next version: will use the Delivery Address - if the customer has - Use Delivery Address when a Delivery Customer.

**Comment by samuelGrahame** [comment]
Will be in the next build - 380

**Comment by samuelGrahame** [comment]
Tested.
