### ISSUE TITLE
Remote Location Manager - Order Set Amounts (Departments)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#284]
This is working, however, if i order for my 2 department, and my default department is 1, it puts the order for the depart 1. Not the department of the technician i am ordering for.

![image](https://user-images.githubusercontent.com/36732084/42978082-90353b22-8bfd-11e8-84a3-707e6b83d253.png)

**Comment by bLeenstra** [comment]
Fixed for v379
