### ISSUE TITLE
Repair Fields - ExtraNumber6 & Date of Manufacture(BuildDate)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#287]
ExtraNumber6 we would use for Samsung new cancellation policy, can we use auto words for this or something similar?

Date of Manufacture is on the GSPN Copy feature, just not imported into BM. this would assist with knowing if a product would be covered by express warranty and scheduling could make a more decisive call on parts ordering etc. so Copy feature would have to be updated to fill in this new field if added.

**Comment by samuelGrahame** [comment]
We can make it so that you can have as many as you want, after 5

**Comment by samuelGrahame** [comment]
In the next version, you can create many extra number fields from the general preferences.

if the caption has the word date in it. it is a date other then that it is a free form text field
