### ISSUE TITLE
Credits vs Orders - Bill Creation

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#29]
- Credits use a "Adjustment Note Number" in addition to the Invoice number, but credits will use the adjustment note number to generate the bill. 

- Will assist with correctly viewing purchase and sales history, available invoices.

- Will also assist with bill creation, currently if the user forgets to update the invoice number field the credit will create new bills for every different invoice number on the credit.

![image](https://user-images.githubusercontent.com/36732084/40159413-cac73488-59db-11e8-9405-02b96ca856d6.png)
![image](https://user-images.githubusercontent.com/36732084/40159451-fa3b8976-59db-11e8-89bb-0405e6be331c.png)
![image](https://user-images.githubusercontent.com/36732084/40159510-38286768-59dc-11e8-95d9-b21523052259.png)

**Comment by bLeenstra** [comment]
Clarifying your requirements here in regards to the bill.
Does the adjustment note get filled out instead of invoice number, or as an additional field on the bill?

**Comment by bLeenstra** [comment]
Will add as setting to use adjustment note over invoice number when generating bills for credits

**Comment by samuelGrahame** [comment]
this will be in the next version , require a setting to be turned on and column - adjustment note number to table
