### ISSUE TITLE
Bulk Reallocate of jobs from Workload Screen - Add filters in top For Charge To, Serviced For & Department. 

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#298]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bLeenstra** [comment]
Included Button to toggle Auto Filter Row to handle Filtering of Charge/Service/Department
