### ISSUE TITLE
Department showing incorrect Purchase and Sales History.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#299]
Hi Guys, Just a quick one. This Sale & Order have thier department set to Adelaide, but the sale is showing in the perth history. Is there any way for this to show correctly?

![image](https://user-images.githubusercontent.com/36732084/43374013-184cd44a-93e0-11e8-8172-47725a4c848f.png)

**Comment by bLeenstra** [comment]
Hi,

The Sales history part of this grid is based on the department set to the actual invoice (which in this instance is Perth, not Adelaide).

If the sale was marked as being a Perth sale, then set to Adelaide after adding this invoice number this would result in the above situation.

**Comment by samuelGrahame** [comment]
Order / Bills would be like that (As a bill is separate to a order). but the sale should show the selected department. I will look into it

**Comment by samuelGrahame** [comment]
it will use the invoice number's used table instead of sales.departmentcntr - fixed in next update
