### ISSUE TITLE
Solvup - Implementation

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#3]
Stage 1:
Implement Copy and Paste of the repair from Solvup Website to Business Manager.
To improve retyping of information on the call centre side.

Stage 2:
Implement Solvup API in Business Manager.

**Comment by bLeenstra** [comment]
Currently in contact with solve-up - have copy of API

**Comment by samuelGrahame** [comment]
Have created an APK for the API. just need to get some training on how it is used in house

**Comment by samuelGrahame** [comment]
added a test import of the csv file.
