### ISSUE TITLE
Pending Repairs - Not grouping by Primary Manager.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#304]
Original request was that we could sort the repairs on the pending screen based on the Primary Manager for that Technician. Currently it does no sorting.

![image](https://user-images.githubusercontent.com/36732084/43495571-6e2a2f2a-956b-11e8-99a3-eb3b506043e4.png)
If i choose Sam Alliston, then nothing appears when all jobs for our Tech named Chris should appear.
**_(Below image is from the Employee Card of the Technician)_**
![image](https://user-images.githubusercontent.com/36732084/43495603-8e2e83de-956b-11e8-9652-5a7c9b57528b.png)

![image](https://user-images.githubusercontent.com/36732084/43495630-c8923098-956b-11e8-9be3-8b7432c448be.png)

**Comment by bLeenstra** [comment]
This managed by field is linked to the customers the selected employee is a manager for, not the technician.
I can add an additional field to the screen so you can filter on technicians the user manages

**Comment by bLeenstra** [comment]
See #151 for additional details

**Comment by bLeenstra** [comment]
Added Additional filter option for v385
