### ISSUE TITLE
Ability to Supersede to a Kit or substitute to a kit

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#31]
Supersede a part to use a kit # or sub to a kit number.

**Comment by bLeenstra** [comment]
Is there any reason / requirement that prevent you from just replacing the items in a kit with the superseded information.
Since our kits replace them selves with the parts listed inside the kit, there is no history you would be preserving by superseding the kit so to speak

**Comment by bLeenstra** [comment]
To be closed if no additional follow up
