### ISSUE TITLE
Comments Box For Customers to See in Online Portal and Can be Triggered in Email/SMS

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#310]
Hi Guys,
Would like a comments box which we can edit that we can use for SMS/Email triggers or to be viewed in our webframe work (BM Light) where we can add comments we only want the customer to see rather than the whole service report. This comments box should also be in the status list and be able to be added in SMS/Email triggers. You can add this as an additional Tab in the same location which the Service Report is located and call it "Report to Customer" Cheers and thanks for your help, you guys are the best.

**Comment by KingjoeTecworks** [comment]
Hi Guys,
Would like a comments box which we can edit that we can use for SMS/Email triggers or to be viewed in our webframe work (BM Light) where we can add comments we only want the customer to see rather than the whole service report. This comments box should also be in the status list and be able to be added in SMS/Email triggers. You can add this as an additional Tab in the same location which the Service Report is located and call it "Report to Customer" Cheers and thanks for your help, you guys are the best.

**Comment by samuelGrahame** [comment]
added new field to the report, will just need to configure your triggers to support them once the update comes out - the field will show in new features list when you login

**Comment by KingjoeTecworks** [comment]
came up with an error. 
![image](https://user-images.githubusercontent.com/39979089/44074350-944c07bc-9fdb-11e8-8c6d-2aff41051efd.png)

**Comment by bLeenstra** [comment]
This needs to be run outside of hours, as it will likely not be adjustable during regular work hours

**Comment by samuelGrahame** [comment]
reason for this, this add's a memo field to the sale/repairs table in the database. once this filed has been added to the database. you can use this on the repair

**Comment by samuelGrahame** [comment]
Has this been added to your database, if not email or call to get this field added.
Status List field has been added - it will be hidden by default.

**Comment by samuelGrahame** [comment]
added report to customer to business manager light. (requires update on server)

**Comment by samuelGrahame** [comment]
Code for SMS report to customer:
```<<ItemReportToCustomer>>```
