### ISSUE TITLE
Hide Option Base on User Profiles

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#311]
Seeing that there has been quite a few additions to the job screen, can a Hide Feature be added for "Features/Fields" which our business does not use. I'm sure a TV/Whitegoods business does not want to See "IMEI Number" as would a IT business not wanting to see "Field Call dates" or "Identify this repair as containing a T2 or New Appliance" whatever that may mean. ETC.
Would make the job screen less painful for training staff and on the eyes.

**Comment by KingjoeTecworks** [comment]
Seeing that there has been quite a few additions to the job screen, can a Hide Feature be added for "Features/Fields" which our business does not use.  I'm sure a TV/Whitegoods business does not want to See "IMEI Number" as would a IT business not wanting to see "Field Call dates" or "Identify this repair as containing a T2 or New Appliance" whatever that may mean. ETC. 
Would make the job screen less painful for training staff and on the eyes.

**Comment by samuelGrahame** [comment]
if we did remove these columns. it would leave blank space's which would not be professional.

imo it would best suited if we had a repair screen for phone repairs/Computer repair's.

as add new fields and hiding some that are their would slow down the screen.

**Comment by KingjoeTecworks** [comment]
so what you are suggesting is booking a repair based on Product Category. this would open a different type of job screen based on category?

**Comment by samuelGrahame** [comment]
i guess having based on product category could be good. as a TV might need different fields to a Phone.

**Comment by samuelGrahame** [comment]
maybe make it custom, where you can say this screen is for: this aka customer/product category/manufacturer.

**Comment by samuelGrahame** [comment]
and design which fields you would like to have on that screen
