### ISSUE TITLE
Bulk Upload to Company Documents

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#312]
would like to upload multiple documents rather than uploading 1 at a time and categorise them during the upload option

**Comment by samuelGrahame** [comment]
Added - Allow Upload Multiple files

**Comment by samuelGrahame** [comment]
if you refresh while uploading
you can categorize them

**Comment by samuelGrahame** [comment]
will be in the next version
