### ISSUE TITLE
Prevent Parts Ordering on Jobs if Not gone through status "Waiting Quote Acceptance" - Permission in Network Control

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#314]
Need a feature which prevents Techs from ordering parts on jobs unless they have been previously in status "Waiting Quote Acceptance"

**Comment by samuelGrahame** [comment]
for this to work, we need to create a reverse permission, as we don't want to disrupt any other customer's.

so for instance:

Don't allow the end user to order part's if the job has not gone through Waiting Quote Acceptance.

Default value will be false. - which will allow other people to operate the same.

**Comment by samuelGrahame** [comment]
would above work for you

**Comment by KingjoeTecworks** [comment]
won't work. because if it has gone through WQA then they won't be able to order parts on any jobs chargeable or warranty

**Comment by samuelGrahame** [comment]
not sure you read what i wrote properly.

i was going to add a permission - don't allow the end user to order parts. if the job has not gone through waiting quote acceptance.

the default will allow all users - currently how it is setup.

**Comment by samuelGrahame** [comment]
^ would the above work, @KingjoeTecworks

**Comment by KingjoeTecworks** [comment]
It won’t work. All good you can close the case.

**Comment by samuelGrahame** [comment]
okay, will do.
