### ISSUE TITLE
Department Hide Feature

### ISSUE THREAD

**Issue by KingjoeTecworks** [IntelogyGroup/BusinessManagerIssues#320]
Hi, Would like a Department Disable/Hide feature for departments which are no longer in use.  It should also hide them from reports.

**Comment by bLeenstra** [comment]
We would likely need to manually adjust every report in your system for this

**Comment by bLeenstra** [comment]
Update: just hiding department from in system drop-downs will sufficient

**Comment by bLeenstra** [comment]
Added for v402
