### ISSUE TITLE
Time Clock Report

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#325]
We have a report in our BM that shows time clocked. 

is there a way we can make the data more relevant. 

![image](https://user-images.githubusercontent.com/36732084/44337936-e818bc00-a4ae-11e8-8b15-35f938623856.png)

Group days, and show total hours for that day and then a total hours for that week in decimal? Tim has an example of the sheet we are using the data for, maybe if you seen it you could manipulate the data to make it easier for our accounts team?

![image](https://user-images.githubusercontent.com/36732084/44337860-b0aa0f80-a4ae-11e8-99ff-4f4f85af30df.png)

I will be available for call on my lunch, just send me hangout and i can call if you require some more information.

**Comment by samuelGrahame** [comment]
when you are available so that i can get a copy of that report, then i can see if i can convert to format given

**Comment by bLeenstra** [comment]
I have created an updated version of this report for you, 
If you give us a call when your free i can add the new report for you

**Comment by AnthonyLorraine** [comment]
Can you call Tim to arrange this or just create new report in our system

**Comment by bLeenstra** [comment]
Added to your reports as Time Sheet Report v2.
Located in same folder as previous time sheet report
