### ISSUE TITLE
Bug Report - Adding Postcode to Tech

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#326]
Operator '=' is not defined for type 'DBNull' and type 'Long'.   at Microsoft.VisualBasic.CompilerServices.Operators.ConditionalCompareObjectEqual(Object Left, Object Right, Boolean TextCompare)   at Intelogy___Business_Manager.v8_DATA_Employee.SimpleButton12_Click(Object sender, EventArgs e)   at System.Windows.Forms.Control.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by samuelGrahame** [comment]
this is fix, will be in the update
