### ISSUE TITLE
Add - Recurring Weekday Call Allotments.

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#327]
Add 7 Check Box's
Add 7 Reason Text Fields to Employee
Add 7 Edit Box to Set Max Call for that day.

If there is a unavailable day it is high priority over these days. aka public holiday.

**Comment by bLeenstra** [comment]
Likely duplicate of #101

**Comment by bLeenstra** [comment]
closed #101 as this thread contains more information regardless
