### ISSUE TITLE
Action Plan or How To - Updating a Repair with information

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#328]
Is there any way to update a repair with a schedule date (say next day) when parts are received for the job. without having to modify the job? 

so if there is already a schedule date on it that has passed or if there is no schedule set, then update to tomorrow, but if it is already a forward date then dont set as it is more than likely confirmed for that date.

thoughts?

**Comment by samuelGrahame** [comment]
so are you talking about receiving parts on a job - from a backorder/ purchase order. or in general part picking.

for this to work. there would need to be code similar to this: 

foreach job in get all jobs that we are receiving that do not have a service call date or the date is below today

  check if next date is available if so then set else continue to the next day...

would this be the logic you are looking for

**Comment by AnthonyLorraine** [comment]
define "Available" 
If available is not a weekend, then yes. 
If available is Day not full, then no. It would be allowed to exceed next days maximum jobs as this would ensure schedulers are checking this job. 

On a separate note in relation to this sequence, I would say that if the service date is a forward date then ignore this, else the call status and field call time would need to be cleared so it isn't mistaken for a confirmed job if moved to the next day
