### ISSUE TITLE
Add Columns for [Reference List]

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#33]
Can the [Reference List] columns be added to the following screens:

Purchase Order Management
Orders & Credits

**Comment by bLeenstra** [comment]
Added to Purchase Order Management screen for v355

Please clarify reference list for  Orders & Credits, as it is already on the order / credit

**Comment by AnthonyLorraine** [comment]
![image](https://user-images.githubusercontent.com/36732084/40215426-fc014c3e-5a92-11e8-91a5-e87074f83579.png)
![image](https://user-images.githubusercontent.com/36732084/40215433-0832737a-5a93-11e8-860b-19eb0db43fd1.png)
![image](https://user-images.githubusercontent.com/36732084/40215440-18cc217c-5a93-11e8-88c9-48e283dc189d.png)

**Comment by bLeenstra** [comment]
Complete in v355
