### ISSUE TITLE
Signature with Service report + after hours report

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#337]
Hi,

 - can you please setup customer signature required with the service report? 
Tech still need to access contact log and change status, clock in & clock out without the signature. 

 - also, we need a report for after hours with customers signatures attached to it.

thank you.

**Comment by sydapp992** [comment]
[TEMPLATE FOR AFTER HOURS_230818.xlsx](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2364095/TEMPLATE.FOR.AFTER.HOURS_230818.xlsx)

This is a sample of the form.  That is needed in Exportable function.

With the signature if the tech attends  twice on the same job, every visit needs to have the signature captured with start and finish time.
When the tech re-attends the previous signature should already be stored in the system & a new signature should be captured with times.

A Monthly summary of all the Before 8.30am or After 5.00pm Weekdays or all of Saturday times should be created as a report that needs to be sent to Samsung.

Last requirement if possible , we can only charge for 1 After Hours claim per job.  Can the report Note/Flag that a duplicate Line exists for that job for the month.

Many Thanks Maria

**Comment by samuelGrahame** [comment]
"every visit needs to have the signature captured with start and finish time." How would we work out the start and finish time, if you don't want it linked to start and stop? and only added to the server report.

**Comment by sydapp992** [comment]
Yes it would be based on start and stop clock please and signature will need to be captured every time.  Once the data has all been collated at the end of the month, I will need the ability to remove lines it they maybe a recall visit or attended twice.  I hope this helps

**Comment by sydapp992** [comment]
Hi Brendan, How are you progressing with this one? thanks

**Comment by bLeenstra** [comment]
No Progress on this currently as we are currently focusing on other high priority tasks
