### ISSUE TITLE
Blank/M000 Serial# not valid - Eworks should prompt tech to update

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#339]
Hi Guys,

Add M000 as not a valid Serial# in EWORKS.

When jobs come from Samsung some jobs come through as M000, which is invalid.
Eworks currently prompts Tech to update EWORKS if the SN# is blank, can it also have validation for M000 that it prompts the technician to update.

Many Thanks Maria

**Comment by samuelGrahame** [comment]
I have added this into Eworks, once tested we can do an update
