### ISSUE TITLE
Secondary Warehouse - Ordering (Remote Location Manager)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#34]
Currently can't order multiple items easily from the Remote Location Manager for a Secondary Warehouse or Remote Location.

Can we select all items required to be re-ordered and add to an order?
if so, can it get the quantities from the Owed area.

else, can you add the ability to select a secondary warehouse in an order/credit screen, so the paste feature can be used.

**Comment by AnthonyLorraine** [comment]
On remote location, can we have issue from secondary warehouse? when secondary w/h is selected it shows that warehouse stock levels?

**Comment by AnthonyLorraine** [comment]
Will this include the ability to re-issue from selected secondary warehouse too?

**Comment by bLeenstra** [comment]
That is a separate issue, i have made #122 to track that

**Comment by bLeenstra** [comment]
Complete for v359
