### ISSUE TITLE
Bin Location Clean-up

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#340]
Filter for Dont Show orders doesn't work, shows no data in that column if not selected.

![image](https://user-images.githubusercontent.com/36732084/45333913-f8522180-b5aa-11e8-83f7-c0de642b4af2.png)

**Comment by bLeenstra** [comment]
Hi Anthony,

At the moment the VanCount and Amount on order column is only loaded when their respective options are selected.

I will adjust this to show this information regardless

**Comment by bLeenstra** [comment]
Included in v397
