### ISSUE TITLE
SMS History Screen not working

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#341]
**Describe the Issue**
Refreshing SMS History Crashes BM

**To Reproduce**
1. Go to 'Tools > SMS History'
2. Click on 'Refresh'
3. See error

**Expected behavior**
Meant to show a list of the SMS sent

**Screenshots**
![image](https://user-images.githubusercontent.com/36732084/45334558-d8702d00-b5ad-11e8-918b-2e2a17d5bcba.png)

**Business Manager Version (please complete the following information):**
 - Version [396]

**Additional context**
Happens for any date chosen

**Comment by bLeenstra** [comment]
You mention see error,

Can you provide a screenshot of the error itself?

**Comment by bLeenstra** [comment]
Fixed v397
