### ISSUE TITLE
Custom Printout Designer

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#342]
![image](https://user-images.githubusercontent.com/36732084/45335415-dc05b300-b5b1-11e8-9c1e-8a866db05e6b.png)

Option to truncate or reduce size to fit inside ? Thoughts on how to prevent what happens in the screen shot?

**Comment by samuelGrahame** [comment]
I will have a look

**Comment by samuelGrahame** [comment]
Maybe change the line alignment to near and not centre - so that it doesn't cut top and bottom

**Comment by samuelGrahame** [comment]
will put in option to have a custom row height

**Comment by samuelGrahame** [comment]
I have added custom row height - will be in next version
