### ISSUE TITLE
PDF Input Management

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#343]
Our electrical suppliers provide invoices with our reference as the job # . As we don't provide order numbers due to the nature of the industry.

If it is stock for our vans the reference used is the van number.

Is there a way this feature could create an order and receive items by dragging the PDF over the Order screen and allocated to the job listed in the "Order Number" field on the invoice?

If stock order can it allocate stock to the van number or tech name? I can give examples via email if needed.

**Comment by samuelGrahame** [comment]
we would have to have a look at the pdf, it could be possible
