### ISSUE TITLE
non moving van stock

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#346]
hi,

can we get a report for non moving van stock return back to warehouse?

thank you

**Comment by bLeenstra** [comment]
Can i get you to clarify further on your requirements for this.
 I need to know what criteria you use for calculating non moving stock

**Comment by sydapp992** [comment]
we're going to give van stock to technicians. i don't want them to hold unwanted / not required stock pass 50 days in the van. i need a report to show parts pass this point.

this is not same as parts removed off the job waiting to return to warehouse.

thank you.

**Comment by bLeenstra** [comment]
I believe the stock level analysis will fulfill your needs here.
Simply select the vans button when opening the screen, choose the van and date range to view over, and enter a value into holding days.
This will break down the stock usage, forecasting how many parts you will need per time period, and suggest a min/max based on this.
You can use this information to request back overstocked parts based on the newly applied min/max
