### ISSUE TITLE
Bigger signature area

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#347]
Signature area is not big enough.

**Comment by bLeenstra** [comment]
Where specifically? Web framework or Business Manager?

**Comment by sydapp992** [comment]
Hi Brendan,

i need a bigger area in BM. we're starting to use the Signature panel it's only allowing same size as the invoice.

current size 18mm x 32mm

![image](https://user-images.githubusercontent.com/39507077/45463628-58ce9380-b750-11e8-8d70-a73a38f2dbc3.png)

**Comment by samuelGrahame** [comment]
We have an ability to design printouts, this includes a way of resizing the signature panels that are printed.

I can talk to Camtec as they have a working copy of our invoice. which i can ask them to share with you.

as above image would remove "Terms of service" and "Payment Terms" which is require by a lot of companies.

(Edited) - thought IGWEB - not BM
