### ISSUE TITLE
Sale Clean-up

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#35]
We currently have a lot of sales in our Estimate Rejected Status, this is a huge task to do as we need to go into each job and add the quote to the attachments + contact log, then remove all quoted parts "Orange Parts" from the sale. Then move the sale to our cancelled status.

Can we:
Add Current Document to the attachments screen + Contact log through the status list (Right Click)
Remove all "Orange Parts" through the status list (Right Click)

or is there an easier way to achieve this?

**Comment by bLeenstra** [comment]
Moving a sale to a cancelled status will not perform stock control on these parts, you can simple move the job to cancelled and finalise

**Comment by AnthonyLorraine** [comment]
![image](https://user-images.githubusercontent.com/36732084/40292565-ad5c74b4-5cfe-11e8-833e-08ddb2a11e2b.png)

i get this error when trying to complete this task. please advise.

**Comment by AnthonyLorraine** [comment]
@bLeenstra Bump :)

**Comment by bLeenstra** [comment]
Simpler to simply allow moving jobs from WQA status to another WQA status when in the statuslist

**Comment by samuelGrahame** [comment]
why didn't people do this procedure when putting it in that status?.

just wondering are we creating something in the program to just clean up once. or is this recurring

**Comment by samuelGrahame** [comment]
^ as we can create a routine to do this.

**Comment by AnthonyLorraine** [comment]
This will eventually build back up as its such a low priority process, if it gets busy this is the first thing to get forgotten. Just thought if i could drag and drop into cancelled then we could just finalise all $0 sales. it would keep the status's clean.

all orange parts would need to be removed after adding current document to attachment screen.
