### ISSUE TITLE
Gas by KG under inventory

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#350]
We need to take GAS as an inventory part#  per KG.  It does not work in the current version of BM.  Can this be fixed?  Thank you

**Comment by samuelGrahame** [comment]
We are working on getting this support, This feature requires us to change a lot of places where we use a Integer value vs a decimal for stock movement. for instances the warehouse location amount is a integer.

we will keep you updated - and tell you once we have this working.

**Comment by sydapp992** [comment]
Any updates on this?  Thank you

**Comment by samuelGrahame** [comment]
we have the changes for this in a fork. because it affects how invoices are used and stored. we need to do further testing to make sure it doesn't break inventory usage.
