### ISSUE TITLE
Upper case

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#354]
convert in to upper case - 

Customer Names - 
Address - 
Part descriptions - 
Check upload manuals named in lower case.

**Comment by bLeenstra** [comment]
Hi,

Can i get you to go into more detail about the issue / feature request here, as it is not clear as to what you are requesting

**Comment by samuelGrahame** [comment]
Done Customer Names - Address.

Will put option to display those fields all in upper case.

**Comment by samuelGrahame** [comment]
(Setting for general Preferences)
     Part Descriptions upper case

**Comment by samuelGrahame** [comment]
added new general preference tab - formatting tab

Setting for Address1 and 2 added to -

**Comment by samuelGrahame** [comment]
This is in then next version of business manager

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/45935838-f0ef3700-bff2-11e8-9476-0084044a8168.png)
