### ISSUE TITLE
Inventory - Flag it indicate a parts should set a repair to major.

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#361]
When specified part is added to repair the repair "Is Major" checkbox is automatically set to true.

**Comment by bLeenstra** [comment]
Added v399

**Comment by sydapp992** [comment]
hi Brendan,

Part for major not working can you please check?

**Comment by bLeenstra** [comment]
This was previously reported and is fixed in v402
