### ISSUE TITLE
Resize photo when tech uploading.

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#364]
When technician uploading photos via web auto resize to smaller scale. 

can we also resize the photos that's already uploaded?

thank you.

**Comment by samuelGrahame** [comment]
Rotating the image in the attachments does resize the images.

to resize the image, the technician will have to view each image.

as they need to confirm that all text/data is visible for warranty purposes.

would that be okay?

**Comment by samuelGrahame** [comment]
This has been completed, When uploading photos - convert to jpg
