### ISSUE TITLE
Action Plan - Add Parameter (Urgent)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#37]
For onSaving can you add Employee Number & Customer charge to Acc Number?

**Comment by AnthonyLorraine** [comment]
Can you also add Payment Terms from the charge customer account. example a non EOM account requires payment made before going to a parts on order status.

**Comment by AnthonyLorraine** [comment]
Can you also add chargeto customer buying group

**Comment by AnthonyLorraine** [comment]
Can Actions plans highlight fields? see example below
 currently im just bombarding people with popups because they dont fill out required information everytime they try save. if it was coloured then they have a better chance of filling out required info prior to saving. less popups same amount of information filled out.

![image](https://user-images.githubusercontent.com/36732084/40216984-e110c580-5a9c-11e8-818d-863b1c8975ea.png)

**Comment by samuelGrahame** [comment]
Hey Anthony, There is a function called set Focus - which allows you to focus on a control.

**Comment by AnthonyLorraine** [comment]
I know about set focus, However it will only show when trying to save. a highlight would be more benificial in reducing the amount of exit save & focus or exit save and messages. If not possible all good, i think we're almost at the amount of popups that people dont even read them anymore, is all.

**Comment by samuelGrahame** [comment]
oh okay, so have on modify, highlight what needs to be done?

**Comment by AnthonyLorraine** [comment]
Yeah.

**Comment by AnthonyLorraine** [comment]
with employee number this will be Primary Allocation Employee Number as when i choose primary allocation it doesn't work with = function but with "Begins With" it works however, begins with webb. if more than 1 webb then i dont know what it will do.

**Comment by AnthonyLorraine** [comment]
Service for state isn't available either. can this be added too?

**Comment by bLeenstra** [comment]
Added action plan for - Primary Allocation Id - Next Update

**Comment by AnthonyLorraine** [comment]
Also, will the color highlights be a possible task?

**Comment by samuelGrahame** [comment]
i will see if possible

**Comment by samuelGrahame** [comment]
we have added highlight action.
works the same way focus does. but highlights the back color
will be in the next version

**Comment by AnthonyLorraine** [comment]
Thank you, dont forget to add all the pretty colours :)

**Comment by samuelGrahame** [comment]
added colours.
will be in the next update

**Comment by AnthonyLorraine** [comment]
@samuelGrahame Colour's work a treat! Still pending on this ticket are the below:

Terms from the "ChargeTo" (Customer Relationship Management)
![image](https://user-images.githubusercontent.com/36732084/41520009-0af566f2-72fe-11e8-8e33-69cfba5b57ca.png)

Account Number "ChargeTo" (Customer Relationship Management)
![image](https://user-images.githubusercontent.com/36732084/41520044-3375d382-72fe-11e8-8233-4dfd516901db.png)

**Comment by bLeenstra** [comment]
Credit Terms and Account Number for charge to have been added to the action plans as of v370.

**Comment by bLeenstra** [comment]
Removed image with identifying inforamation
