### ISSUE TITLE
Asset Management show name of the person

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#371]
In asset management show the persons name not just by the location. 

also need to have issued date to person & returned date.

**Comment by samuelGrahame** [comment]
Issue Date and Returned date were not recorded in a extract format - they were logged but not only in the event viewer - i have created these fields.

you will need to install these fields related to asset manager on load up

**Comment by samuelGrahame** [comment]
this will be in the next version - as long as you install this feature

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/49048425-cf970b00-f22e-11e8-96b8-9c37eec1d44a.png)
