### ISSUE TITLE
Rates by Charge to Account/Product

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#372]
We would like Rates/Charge Amount to be tracked/appear in Financial Details based on Charge to Account & Product Type.   We are currently tracking Rates manually.  
This would be a great benefit in the system.  Thank you

**Comment by sydapp992** [comment]
Any updates on this?  We have many different rates on pieces of papers.  It would be great to consolidate this in BM thanks

**Comment by samuelGrahame** [comment]
do you have an excel sheet so i can see what types of charges you have.

is it just the labour rate or things like service fee etc
