### ISSUE TITLE
Copying Part# does not work when parts are at the Top of Inventory (within job)

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#373]
In Inventory section of a job, when right click and select copy part# it does not work.
We are currently only able to copy part# by highlighting the part and then copying manually.
Could this be fixed thanks
[part#.docx](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2618165/part.docx)

**Comment by samuelGrahame** [comment]
this has been fixed, will be in the next version of bm
