### ISSUE TITLE
Head Technician Access in EWORKS without providing Full Administration Functions

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#374]
We would like our Head Technician Access in EWORKS to view all repairs by other techs.
The same Technician will also working from the office in the system and we do not want to give him Full Administration Functions/Access to data.
Can a feature be created to resolve this issue.  Thank you

**Comment by bLeenstra** [comment]
You can select the "This employee is an online claims moderator" checkbox in the employee management screen.
This will allow him to view any job inside the webframework
