### ISSUE TITLE
Samsung Parts Pricing Update

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#38]
@samuelGrahame as discussed. Save GSPN login details within the Employee Card. Then when query on part number, logs you into gspn and looks part# up and gets price. sets the "As of" date to current date.

Unsure if this could be done with bulk part numbers, maybe a program can be run every night to update pricing. Need to discuss while logged into gspn.

**Comment by samuelGrahame** [comment]
Closed because of SC

**Comment by AnthonyLorraine** [comment]
SC?
