### ISSUE TITLE
Sales - Unit Identification (Model Code)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#41]
Can the sales screen have Model Code added to it too? this isnt a linked to anything field is it, so i could make this mandatory through action plans but if cust couldnt supply then we could add NA and it wont affect any data.

Also, would it hurt to have the serial number on sales too, could then view history or link sales to repairs through this too. just a thought. if so , can you add to that history button cardtype sale or repair to make it easier to identify?

![image](https://user-images.githubusercontent.com/36732084/40216711-fa816094-5a9a-11e8-93d3-afe42cc16b16.png)

**Comment by bLeenstra** [comment]
Added for v367

**Comment by bLeenstra** [comment]
Delayed to v368
