### ISSUE TITLE
Import Days Unavailable - New Users

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#56]
Need to be able to fill in the Public holidays if we create a new technician. Also based on State as the holidays are different depending on the states.

**Comment by samuelGrahame** [comment]
if we match this format is this okay:

https://data.gov.au/dataset/australian-holidays-machine-readable-dataset

**Comment by AnthonyLorraine** [comment]
This is our current format, so having more information wouldn't hurt? Cant you just import the dates with the reason as the name of the holiday. If tech = WA then import WA codes, If Tech is SA then import SA?

![image](https://user-images.githubusercontent.com/36732084/41268745-40f883c0-6e34-11e8-8d31-15fe1d8ea94d.png)

**Comment by bLeenstra** [comment]
added v398 - button to load public holidays added to days unavailable screen.
Need to select state for tech during this
