### ISSUE TITLE
Merge to existing credit - Only does one line at a time

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#57]
as described.

moving items from credit to credit only works for 1 item at a time. selecting all and clicking merge to existing credit, refreshes as it has done something but nothing.

**Comment by bLeenstra** [comment]
Hi Anthony,

Are the items you are trying to merge to a new credit already set as awaiting approval or returned?
As items in these states cannot be merge into another credit.

I was unable to create a situation where only 1 item was merged to a new credit, unless out of the items i had selected only 1 was not already awaiting approval or returned, which is intended.

**Comment by AnthonyLorraine** [comment]
awaiting approval as it already has an invoice number assigned to it.

**Comment by samuelGrahame** [comment]
this now supports merging reserve items for credits.
also i noticed that the create new will merge received items. this has been blocked.
