### ISSUE TITLE
Inputting another state information, cant find in the search.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#58]
![image](https://user-images.githubusercontent.com/36732084/40292725-7b6ca9c8-5cff-11e8-896e-05e4a43c4e02.png)

Do i have to import the south australian postcodes somewhere to enable the postcode search to include those suburbs? 

Currently to get salisbury to work on the above example i need to type SA in first, then postcode. sometimes works.

**Comment by bLeenstra** [comment]
When the state label is filled out it limits the suburbs to that state,
if you remove the WA state the SA states will repopulate

**Comment by AnthonyLorraine** [comment]
Brand new employee had nothing in there. when i typed salisbury it prefilled the closest named WA Suburb. didnt auto select from SA table.

**Comment by bLeenstra** [comment]
Please check general preferences -> service report -> default country / state.
If WA is listed there this will be limiting the available localities to WA unless you manually override.

You can add SA if this is the case by changing the value to "WA, SA"

**Comment by AnthonyLorraine** [comment]
this worked great. thank you. sa,wa without ""
