### ISSUE TITLE
Web Framework - Setting to enforce the serial number and signatures to be filled out

### ISSUE THREAD

**Issue by bLeenstra** [IntelogyGroup/BusinessManagerIssues#59]
Should prevent tech from saving until these areas are filled out

**Comment by samuelGrahame** [comment]
"We really need a solution to force signatures and serial numbers to prevent issues with our warranty payments. " quote from the customer

**Comment by AnthonyLorraine** [comment]
does this not already do that, but without signature option?
Tim had requested this a while ago.
![image](https://user-images.githubusercontent.com/36732084/40337094-132ee7a8-5da0-11e8-9def-bf008f3865c6.png)

**Comment by bLeenstra** [comment]
Complete with webframework build after this date, requires setting in BM to be set aswell
