### ISSUE TITLE
Display Custom Printouts on Repair/Sale

### ISSUE THREAD

**Issue by samuelGrahame** [IntelogyGroup/BusinessManagerIssues#64]
Display the custom printouts that are made using the custom designer in the repair/sale

**Comment by AnthonyLorraine** [comment]
Can it be added to orders too for the part labels?

**Comment by samuelGrahame** [comment]
This has been completed,. required for testing

**Comment by samuelGrahame** [comment]
"Can it be added to orders too for the part labels?"

It will be, i need to Finished the SQL and Binding Data for orders
