### ISSUE TITLE
Job Label - Secondary warehouse location

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#65]
![image](https://user-images.githubusercontent.com/36732084/40341025-3ec1b714-5db5-11e8-9036-60354043eea3.png)

can it have if secondary warehouse, show that warehouse bin location?

**Comment by samuelGrahame** [comment]
this will now work with the custom label designer for parts label. in the binding data. you can specify

fromlocation.bin, name. tolocation.bin,name etc

i will be making the template for above soon. - or it can created by you in the next update if you would like

**Comment by AnthonyLorraine** [comment]
If i create will we be able to print from Orders?

**Comment by samuelGrahame** [comment]
if you print parts label and not job label from orders it will work

**Comment by samuelGrahame** [comment]
use the parts label designer.

**Comment by bLeenstra** [comment]
Removed images with identifying information
