### ISSUE TITLE
Bug Report - Email using Internal Address book.

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#66]
Column 'WorkEmail' does not belong to table Employees.   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)   at Intelogy___Business_Manager.v8_DLG_AddressBook.Select_Employees(Boolean DoubleClick)   at Intelogy___Business_Manager.v8_DLG_AddressBook.GridControl1_DoubleClick(Object sender, EventArgs e)   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)   at DevExpress.XtraGrid.GridControl.OnDoubleClick(EventArgs ev)   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by bLeenstra** [comment]
fixed in v357
