### ISSUE TITLE
Stock Dialogue - Sales

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#72]
Guys, when the below option is enabled can we have it so we can still use the option to Transfer items from warehouse to allow the Picking slips screen to be utilised?

![image](https://user-images.githubusercontent.com/36732084/40348563-9e88cc16-5dd6-11e8-95a8-a30cca8134a3.png)

![image](https://user-images.githubusercontent.com/36732084/40348502-79e52238-5dd6-11e8-8610-f86f21422083.png)

**Comment by bLeenstra** [comment]
for the transfer option we need a second location we are transferring to. where would that be in this senario?

**Comment by samuelGrahame** [comment]
Always transfer your Inventory from a location. tick that. then choose the location, this can be set per user or globally - globally is in general preferences.
location would be cash sales/ counter etc

**Comment by bLeenstra** [comment]
Removed images with identifying information
