### ISSUE TITLE
Remote Inventory  - Show items to be Returned on EWORKS

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#73]
On EWORKS we would like technicians to be able to see what parts need to be returned - which can be printed by the techs.  Replica of report that exist in BM.  
In addition, can there be categories added to the end of of sheet  - 
Quantity | New | Faulty | Wrong | Date Returned.  
It would be great to select online before printing or just to have these categories on the print out.
THANK YOU

[Returns sheet.xlsx](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2028587/Returns.sheet.xlsx)

**Comment by bLeenstra** [comment]
This will be likely added by filtering existing rows with a button added to the screen
