### ISSUE TITLE
copy field - samsung saw request - service authorisation

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#75]
Create a button that pulls the below data
We need to manually copy and paste from BM into Samsung System.  Can there be a POP UP button that pulls, like a Sticky Note
Fault Reported: - directly from BM
Model No: - directly from BM
Serial No: - directly from BM
Date of Purchase: - directly from BM
Purchased From: - directly from BM
Does customer have POP - YES (This should be pre-populated with a YES)
Please cover under ACL for parts and Labour (This should be pre-populated with this note)
THANK YOU

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/40693232-ba52908e-63f9-11e8-945b-a65bd41ba20e.png)

then just click it:

![image](https://user-images.githubusercontent.com/13449963/40693241-c3cc154a-63f9-11e8-93ba-c83f355320e8.png)

**Comment by samuelGrahame** [comment]
this will be in the next update
