### ISSUE TITLE
copy field - samsung saw request - exchange 

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#76]
Create a button that pulls the below data
We need to manually copy and paste from BM into Samsung System. Can there be a POP UP button that pulls, like a Sticky Note  THANK YOU

[COPY FIELD - SAMSUNG SAW REQUEST - EXCHANGE.xlsx](https://github.com/IntelogyGroup/BusinessManagerIssues/files/2028755/COPY.FIELD.-.SAMSUNG.SAW.REQUEST.-.EXCHANGE.xlsx)

**Comment by samuelGrahame** [comment]
![image](https://user-images.githubusercontent.com/13449963/40692906-d00a888e-63f7-11e8-8be8-785f037dd42b.png)

If the repair charge to customer is Samsung a button under actions. called create samsung saw request

![image](https://user-images.githubusercontent.com/13449963/40692934-fe9f4c5c-63f7-11e8-8bda-3a5b63b23061.png)

The Following popup will be generated

**Comment by samuelGrahame** [comment]
The job i used doesn't have any information that is why it is blank
