### ISSUE TITLE
accounts receivable - statements / function

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#77]
Recently started using ACCOUNTS RECEIVABLE - Email Statement to ALL Debtors - This function is Fantastic (Big time saver)
A few suggested changes
1. When creating a COD job can there be a Default to save Email address from Primary Contact Detail to Accounts Detail Email.  Last month I needed to manually go into the Ledger for All Business/COD/Real Estate and copy from one section to the other to be able to use the this function
2. A log needs to be created under "Contact History"  to prove that a statement has actually been sent. Only an Online Pop up come ups. When contacting the Debtor we need to know when the statement was sent or have some kind of Reference.  (I am getting notification for any emails that are invalid through my email)
3. Some Debtors require copies of the invoices attached to the Statement.  Can this be added feature in the Menu under Print/Email - Statements attached with Invoices
4. Can I add a Standard Template Email with the Statement - Dear Customer / Accounts, Please find attached .....................................

**Comment by bLeenstra** [comment]
Hi Just addressing point 2.
This was added in issue#20, and are currently recorded in the system.
However currently there is no way to view them, i can see to adding this to the customer event viewer

**Comment by samuelGrahame** [comment]
To point 1, I will make it so, if custom is COD and no Accounts email, use primary email instead. will be in the next update.

**Comment by sydapp992** [comment]
Brendan I think this has alll been done now? close? thanks
