### ISSUE TITLE
Search Function in Reports

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#78]
Can a Search Function in Reports be Added?

**Comment by samuelGrahame** [comment]
because there are passwords/ lockable folders and files. to have a just normal filter would popup the passwords dialogs.

I can how ever add a search button, so that you can type the report name in. then if you go to open the report. you will have to enter in the password.

**Comment by samuelGrahame** [comment]
This has been completed, will be in the next version
