### ISSUE TITLE
Lumley / The Warranty Group - Copy PDF Function

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#79]
Create a Copy/Paste function for the Lumley / The Warranty Group Service PDF requests

**Comment by samuelGrahame** [comment]
if you would like to send us a copy of a service request. so that we can create these for you.
also if you give us the charge to lastname when creating these repairs. (email to samuel@intelogy.com.au))

**Comment by bLeenstra** [comment]
This was done in v354 - please refer to email
