### ISSUE TITLE
When Exporting PDF from repair printout - Change file name to list customer Account / Repair Number

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#81]
Please kindly create Print PDF Invoices - with an Automatic Label with Charge to Account & Repair No.

**Comment by samuelGrahame** [comment]
need more information, "Automatic label" not sure what you mean. do you want to print a label with the charge to account and repair no?

**Comment by sydapp992** [comment]
Yes please, when selecting receipts thanks

Kind Regards
Maria Khalil

(Please Note: I am in the office on Mondays to Friday from 8.30am to 2.30pm, for any urgent matters please call me on my mobile or email service@sydneyappliance.com.au<mailto:service@sydneyappliance.com.au>)
Maria Khalil | Sydney Appliance Service
992 King Georges Road, Blakehurst NSW 2221
É: (02)9546-4444
É: (02)9546-7415
É: 0425-250-730
•: maria@sydneyappliance.com.au<mailto:spares@sydapp.com.au>
ü: www.sydneyappliance.com.au<http://www.sydneyappliance.com.au/>

PLEASE LEAVE YOUR FEEDBACK HERE<https://goo.gl/GdDGNi>
https://goo.gl/GdDGNi

[follow-us-on-google-e1331109379705]<https://plus.google.com/b/100510948389501294835/+SydneyApplianceServiceBlakehurst>[cid:image003.jpg@01D3F2D7.694A16F0]<http://www.sydneyappliance.com.au/>

**Comment by samuelGrahame** [comment]
you can create your own label now, will look into having an option to print the label when printing a docket.

**Comment by bLeenstra** [comment]
Changed title to correctly reflect question

**Comment by samuelGrahame** [comment]
This has been completed - will be in the next version of business manager

**Comment by samuelGrahame** [comment]
Int Printing options you can set default to be [AccountNumber]_[RepairNumber].pdf
if this setting is not ticked it will be regular: Repair_[RepairNumber].pdf
