### ISSUE TITLE
Finalise Repair when parts are in Red at bottom (when tech has not fitted parts)

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#86]
1. To be able to Finalise Repair when parts are in Red at bottom (when tech has not fitted parts).
2. For Picking Slip Return from Van stock - Need to have a save button before part disappears.  Checklist of all items ticked before the return happens

**Comment by bLeenstra** [comment]
Info: jobs with parts being returned from van cannot be finalised as there are quesaleitems.
Need a work around as vans may not be in to return parts before repair needs to be invoiced out

**Comment by samuelGrahame** [comment]
"For Picking Slip Return from Van stock - Need to have a save button before part disappears. Checklist of all items ticked before the return happens", there is a multi selection, that will allow you to work like that. etc print a list. if you return with the check edit it will return then and there.

"To be able to Finalize Repair when parts are in Red at bottom (when tech has not fitted parts)."

this can be done.

**Comment by samuelGrahame** [comment]
this has now been completed , will be in the next version of business manager
