### ISSUE TITLE
USB Touch Panel for Signature 

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#87]
Will a USB Touch Panel be compatible with BM for Signature  - customers collecting from counter.  What device is recommended?

**Comment by bLeenstra** [comment]
Are you talking about USB drawing tablets, or a custom signature drawing device?
The answer is this ultimately depends on the device being used.

**Comment by bLeenstra** [comment]
Further to this, its its simply a drawing tablet, i could make a button in the repair that you press and it will take all input from the device as the signature - although this would still depend on the device

**Comment by AnthonyLorraine** [comment]
we use this. works fine, however the drawable area on the physical product needs to be defined to match the input area on Business manager. We have had some stickers made for the top of these signature pads. when they arrive i can show if needed.

https://www.ebay.com.au/itm/302236531594?ul_noapp=true

**Comment by samuelGrahame** [comment]
going to close this, because a suggested signature panel was shown
