### ISSUE TITLE
When tech is changed - stock movement Trigger to warehouse

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#88]
When a tech is off sick, job is re-allocated to another tech.  Stock can be automatically transferred through the system.  Physically, the stock is still sitting with the old tech the Bay, system shows new tech already has part.  How does the warehouse get an Alert, through a status change/Picking Slip?

**Comment by bLeenstra** [comment]
Notes: When part is transferred to van in BM, it is actually sitting in a bin for that tech to collect in their warehouse. When changing tech, they want to notify the warehouse staff to move this part to the new technicians bin. --- could just be a transfer status between technicians

**Comment by bLeenstra** [comment]
Users can no longer change allocated technician when parts are set without permission to account for this.
Eventually we will be adding a process to show this within the system
