### ISSUE TITLE
Emailing Employees from Business Manager (Add to Contact Log)

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#9]
At the moment we email the tech from our google.mail server and then we copy paste the email body into the contact log, this task can sometimes be forgotten by the user.

Is it possible to use the built in mail system in Business manager then use the emails stored within the employee contact screen to populate the address book in that built in email. so i don't have to type the employee email address each time.

Can any email body sent by the email system in Business Manager add its information the the repair, order or sale contact log?

**Comment by samuelGrahame** [comment]
if you are using the inbuilt email client, we can add to the contact. if using outlook we cannot. as they throw exceptions say a virus is tryinh to get what you typed etc.

**Comment by AnthonyLorraine** [comment]
We use inbuilt client, maybe if anyone uses inbuilt client option it will enable add to contact log :+1:

**Comment by samuelGrahame** [comment]
send email body to contact, for sales,repairs.

**Comment by samuelGrahame** [comment]
added - show addressbook for TO.CC, BCC buttons.

**Comment by samuelGrahame** [comment]
will be in the next version.
