### ISSUE TITLE
Concerned Tick - Audit Trail

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#90]
Need to see when Concerned Tick is added date & by who in Contact Log or Event Activity.  Who removes it / date (whether this is from EWORKS/BM) THANK YOU

**Comment by samuelGrahame** [comment]
Added to Business Manager: will be in the next update: To Event Activity
Need to add to eworks.

**Comment by AnthonyLorraine** [comment]
@samuelGrahame or @bLeenstra Can this feature be added to camtec eworks too?

**Comment by samuelGrahame** [comment]
this will be for everyone

still need to add it for the framework

**Comment by samuelGrahame** [comment]
Web Framework has been updated.
we will need to update the web framework on the customer's severs for this to work.
