### ISSUE TITLE
Sales - Delivery Allocation (Not Filled Out) **Action Plans**

### ISSUE THREAD

**Issue by AnthonyLorraine** [IntelogyGroup/BusinessManagerIssues#91]
I still get the popup note and exitsave() applied even when delivery allocation is filled out. Am i referencing the wrong field?

![image](https://user-images.githubusercontent.com/36732084/40400213-bf51c252-5e73-11e8-8505-9d92c9805296.png)

![image](https://user-images.githubusercontent.com/36732084/40400192-a5336d80-5e73-11e8-9e31-76d487db3312.png)

**Comment by bLeenstra** [comment]
Issue: delivery allocation no backing code in action plan for sale

**Comment by bLeenstra** [comment]
Fixed for v359
