### ISSUE TITLE
Control c - telephone does not work correctly in customer contact

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#94]
Please assist 

Control   c - telephone does not work correctly in customer contact  THANK you
--

**Comment by bLeenstra** [comment]
Issue: CTRL + C shortcut not added text selected from contact field to clipboard on customer card - further investigation required

**Comment by samuelGrahame** [comment]
This has been fixed, will be in the next version

**Comment by samuelGrahame** [comment]
I have removed the function that blocks control + c from entire program. will be fixed next version. previous - i only removed from customer screen not repair
