### ISSUE TITLE
scanning stock in part into stock 

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#96]
Can the warehouse Scan the part#, Scan the Van#, Then Scan Transfer In. This to avoid/limit error from warehouse

**Comment by samuelGrahame** [comment]
I think scanning the Part is good. but for scanning the van. it think it would be better if in the barcode control. you choose the van. 
otherwise there might be errors where you scan the wrong van. etc we also would have to have  a sheet to have a list of all the van's.

what are your thoughts?
