### ISSUE TITLE
Cant be in Edit Mode while Viewing Attachments

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#98]
Please assist with this important change - we need to be in Edit Mode while Viewing Attachments to be able to add SN/DOP ETC

**Comment by bLeenstra** [comment]
Issue was actually intended to be have the attachments screen as a non dialog

**Comment by bLeenstra** [comment]
Attachments form needs to be a dialog as to update the screen once the attachments screen is closed with the new attachments count.
For this to be possible as a non dialog i would need a way to prevent closing the repair / sale while the attachments screen is open

**Comment by samuelGrahame** [comment]
I think the better solution would be allow to enter the serial number / warranty purchase date from this screen.

**Comment by samuelGrahame** [comment]
because of how the attachment screen gets used in other location's in the system.

**Comment by samuelGrahame** [comment]
what other fields do you need to add?

**Comment by samuelGrahame** [comment]
The screen is no longer a dialog/ doesn't stop input for the repair.
i also added, if the repair is in modify, added the fields to edit next to the display image.
etc serial and dop
![image](https://user-images.githubusercontent.com/13449963/40406236-418c3b38-5ea3-11e8-9616-f99615d2e407.png)

**Comment by samuelGrahame** [comment]
will be in the next update
