### ISSUE TITLE
Out of Area Charges

### ISSUE THREAD

**Issue by sydapp992** [IntelogyGroup/BusinessManagerIssues#99]
Please add another column under Data Management/Zone Items for Out of Area Charges 
For Example - A particular postcode attracts a charge of  $37.44.  We need to save the distance in the system TRAVEL 28.8KM= $37.44 .  We are currently using the Description field but this should be used for time.  
If this column can be added, we need the info to be displayed
1. On run schedule, Staff will need to see which job is the furthest distance (only 1 can be claimed). They will manually need to pick this. 1 travel claim per Tech per Day
2. Can an indicator be created, to show Travel has been claimed on that particular job (also visible on run schedule)
2. The distance TRAVEL 28.8KM= $37.44 also needs to be in a field that can be copied into GSPN/other manufactures
3. Just checking - Can the system do it own calculation from our address to the customer's address - less 60km x $1.30 radius to work out the distance

**Comment by samuelGrahame** [comment]
"Just checking - Can the system do it own calculation from our address to the customer's address - less 60km x $1.30 radius to work out the distance"

we can but we require the GPS in the system, for new postcodes. there won't be any GPS data to that postcode. - in the import manager, -> ribbon -> Data -> Update Postcode Data.

**Comment by samuelGrahame** [comment]
We do not have a field called - Travel to have travel claimed we would need to have a field just for travel in the system. because the distance can't be allocated 100% of the time. need to work out how to treat this
